{-# LANGUAGE LambdaCase #-}
module Compiler where

--Imports the modules for each step, handles running the pipeline

--String -> CST
--Generated by BNFC
import E.Par (pM,myLexer)
import E.ErrM (Err(..))
import E.Abs (Ident(..),UIdent(..),Infix(..),OS(..))
import qualified E.Abs as P
--CST -> AST
import DTs
import Data.Map (Map(..))
import qualified Data.Map as M
import Control.Monad.Trans.Except
import Control.Monad.State
import Text.Read (readMaybe)
--Desugaring code written in Compiler... maybe todo move
--AST -> IR
import IR1 hiding (Ifte,While,Return)
--IR -> CFG (non-stack aware)
--TODO rename...
import ToyCFG
--CFG2 -> Asm
import Stack
--Asm -> Bytecode
import Asm (Asm(..),AsmError(..),assemble,toExe)
import qualified Asm as A (Label(..))
import Data.Set (Set(..))
import qualified Data.Set as S
--For debugging:
import Pretty
--For file output
import Data.Char (intToDigit)

--A simple compilation function; takes a file and produces a .evm.txt
--file containing the bytecode. Prints the error if compilation fails or if
--there are undefined labels.
--The bytecode produced by an EVMC module is not inherently a creation script;
--to deploy with create rather than setcode then code object values must be
--added to the language.
--Constructor parameters require an end pointer.

--Params: source file, dest path, output name
--
compile :: FilePath -> FilePath -> String -> IO ()
compile src dest nm = do
  str <- readFile src
  case pipeline2Bytecode str of
    Left err -> putStrLn $ "Compiler error: \n" ++ show err
    Right (s,bs)
      | s /= S.empty -> putStrLn $ "Undefined labels in program: " ++ show s
      | let -> do
          putStrLn $ "Compilation OK, writing to " ++ dest
          writeFile (dest ++ "/" ++ nm) $ "0x" ++ toHexString bs
  where toHexString bs = do
          b <- bs
          [intToDigit $ b `div` 16, intToDigit $ b `mod` 16]
      
--Now for some basic testing, using past failing cases
testModules :: [String]
testModules = [
  --The case below failed because of a bug in dfsR2L. Now it generates correct
  --but inefficient bytecode: 2 more swaps than necessary.
  "module {main:Int Unsigned 8->Int Unsigned 8;main x := return (1+x)}",
  "module {main:Int Unsigned 8->Int Unsigned 8;main x := main x}",
  "module {main:()->();main _ := main()}",
  "module {main:()->Int Unsigned 8;main _ := return 0}",
  "module {main:Int Unsigned 8->();main x := return ()}"
              ]

printIRM :: String -> IO ()
printIRM str =
  case pipeline2IR str of
    Right irm -> mapM_ putStrLn $ prettyIRM irm
    Left err -> putStrLn $ "Error: " ++ show err
--TODO dedup...
printCFG :: String -> IO ()
printCFG str =
  case pipeline2CFG str of
    Right (_,cfgm) -> mapM_ putStrLn $ showCFGM cfgm
    Left err -> putStrLn $ "Error: " ++ show err
--Doesn't display the version count or substitution maps.
printCFG2 :: String -> IO ()
printCFG2 str =
  case pipeline2CFG2 str of
    Right (_,cfg2m) -> mapM_ putStrLn $ showCFG2M cfg2m
    Left err -> putStrLn $ "Error: " ++ show err
printAsm str =
  case pipeline2Asm str of
    Right asms -> mapM_ (putStrLn . prettyAsm) asms
    Left err -> putStrLn $ "Error: " ++ show err

--Putting it all together (in progress):
data CompilerError = ParserError String
                   | DesugarError DError
                   | SeqError SeqError
                   | IllFormedCFG Name [IR]
                   | AsmError String
                   | BytecodeError AsmError
  deriving (Eq,Ord,Read,Show)

--The string set is a warning of undefined labels; none should exist
pipeline2Bytecode :: String -> Either CompilerError (Set String, [Int])
pipeline2Bytecode str = do
  asm <- pipeline2Asm str
  objectFile <- assemble asm ? BytecodeError
  return $ toExe objectFile
pipeline2Asm :: String -> Either CompilerError [Asm]
pipeline2Asm str = do
  (stat,cfg2m) <- pipeline2CFG2 str
  funasm <- compile2asm cfg2m ? AsmError
  let statasm = do
        (label,(_t,labels_bytes)) <- M.toList stat
        PlaceLabel (A.LNamed label) :
          map (\case Left (lab,len) -> UseLabel len (A.LNamed lab)
                     Right byte -> Bytes [byte])
          labels_bytes
  return $ funasm ++ statasm
pipeline2CFG2 :: String ->
                 Either CompilerError
                 (Map Name Static, Map Name (Arity,(Label, CFG2)))
pipeline2CFG2 str = do
  (stat,cfgm) <- pipeline2CFG str
  let cfg2m = M.map (\(arity,((lab,_live),cfgs)) ->
                          let cfg = labelSLCMap cfgs
                              (_,cfg') = processCFG (lab,cfg)
                          in (arity,(lab, opt2 lab cfg')))
                 cfgm
  return (stat,cfg2m)
--The CFG logic doesn't care about arity, so it can be passed through the
--CFG and CFG2 steps unchanged
--It doesn't care about statid data either, so I just pass it through
--unchanged.
pipeline2CFG :: String -> Either CompilerError
  (Map Name Static, Map Name (Arity,(LL,CFGS)))
pipeline2CFG str = do
  irm <- pipeline2IR str
  let ds = M.toList $ irDefuns irm
  fcfgs <- mapM (\(f,(arity,irs)) ->
                   case ir2cfg irs of
                     (Just ll, cfgs) -> return (f,(arity,(ll,cfgs)))
                     _ -> Left $ IllFormedCFG f irs) ds
  return (staticData irm, M.fromList fcfgs)
  
--Compiles all the way to structured IR
pipeline2IR :: String -> Either CompilerError IRModule
pipeline2IR str = do
  m <- parseModule str ? ParserError
  mod <- desugar m ? DesugarError
  irmod <- seqModule mod ? SeqError
  return irmod
  --I need to generate IR for each function called from main
  --Seq only handles a single function's IR codegen

(?) :: Either localErr a -> (localErr -> globalErr) -> Either globalErr a
Right b ? _ = Right b
Left err ? errt = Left $ errt err
--Parse a module from string
parseModule :: String -> Either String P.M
parseModule str =
  case pM $ myLexer str of
    Ok mod -> Right mod
    Bad errStr -> Left errStr

data DError = TySigDefunMismatch Name Name
            | DuplicateDefun Name
            | BadDOrdering [P.D]
            | BadOpInType String
            | BadEInType P.E --catch-all error for desugarT
            | BadEInPat P.E --same for desugarP
            | BadDoInDesugarS [P.S]
            | AssignIsNotAnE P.E P.E --for now
            | DuplicateDeclsForName Name
            | DuplicatePads Padding P.Field
            | DuplicateAligns Padding P.Field
            | CoerceMixedWithOps [Name]
            | GenericDError String
  deriving (Eq,Ord,Read,Show)
desugar :: P.M -> Either DError Module
desugar (P.Module ds) =
  case runState (runExceptT $ desugarDs ds) $
  Module {defuns = M.empty,
          tysyns = M.empty
         } of
    (Left derr, _) -> Left derr
    (Right (), m) -> Right m
--Every defun f must be preceded by a tysig f : t; together they become one
--DT.Defun.
--Duplicate defuns are an error.
type De = ExceptT DError (State Module)
desugarDs :: [P.D] -> De ()
desugarDs [] = return ()
desugarDs (P.TySyn conargs te : rest) = do
  let (nm,args) = desugarConArgs conargs
  t <- desugarT te
  modify (\m -> m{tysyns = M.insert nm (args,t) $ tysyns m})
  desugarDs rest
desugarDs (P.TySig (Ident f) t :
           P.Defun (Ident f') lhs s :
           rest)
  | f /= f' = throwE $ TySigDefunMismatch f f'
  | let = do
          checkForDuplicates f
          t' <- desugarT t
          --Note patterns are a subset of syntactically valid Es
          p <- desugarP lhs
          --Need to add do block support to DTs?
          block <- desugarBlock s
          let def = Defun f t' p block
          insertDefun f def
          desugarDs rest
desugarDs other = throwE $ BadDOrdering other

--No decls (functions, tysyns, datatypes, globals, immutables...) may shadow
--each other.
checkForDuplicates :: Name -> De ()
checkForDuplicates nm = do
  m <- get
  --TODO give a more informative error message
  if S.member nm $ S.unions $
    [M.keysSet $ defuns m,
     M.keysSet $ tysyns m,
     primTyCons]
    then throwE $ DuplicateDeclsForName nm
    else return ()
insertDefun :: Name -> D -> De ()
insertDefun f def =
  modify (\m->m{defuns=M.insert f def $ defuns m})

desugarConArgs :: P.ConArgs -> (Name,[Name])
desugarConArgs = \case
  P.CANil (UIdent nm) -> (nm,[])
  P.CACons cargs (Ident arg) ->
    let (nm,args) = desugarConArgs cargs
    in (nm,args++[arg]) --Tiny inefficiency

{-
type SInt = Int Signed
type UInt = Int Unsigned
T ::= Int signedness n
    | T -> T --only op allowed
    | {(T | field:T),...}
FW: Ptr, unparam'd user types
-}
desugarT :: P.E -> De T
desugarT = do
  let r = desugarT
  \case
    --Assign makes no sense in type context
    P.Ops a (Infix "->") os -> do
      at <- r a
      bst <- desugarArrowOps os
      return $ foldr1 (\a b -> a :-> b) $ at:bst
    --There are no type-level prefix ops
    P.App e1 e2 -> (:$$) <$> r e1 <*> r e2
    P.Con (UIdent nm) -> return $ TyCon nm
    P.Var (Ident nm) -> return $ TyVar nm
    --No dot
    P.Int n -> return $ TyNat n
    P.EmptyTup -> return $ tupleT []
    P.Tup e es -> tupleT <$> ((:) <$> r e <*> mapM r es)
    P.EmptyStruct -> return $ Struct []
    P.EStruct fields -> Struct <$> mapM desugarFieldT fields
    --No wild
    e -> throwE $ BadEInType e

desugarArrowOps = \case
  OSNil a -> (:[]) <$> desugarT a
  OSCons a (Infix "->") os -> do
    at <- desugarT a
    bst <- desugarArrowOps os
    return $ at : bst
  OSCons a (Infix inf) os -> throwE $ BadOpInType inf
--TODO add padding keywords to syntax; for now bytepad default is mandatory
desugarFieldT :: P.Field -> De (Field T)
desugarFieldT = desugarField desugarT
desugarFieldE :: P.Field -> De (Field E)
desugarFieldE = desugarField desugarE
{-
desugarFieldT = \case
  Named (Ident nm) e -> do
    t <- desugarT e
    return (Byte, Just nm, t)
  Anon e -> do
    t <- desugarT e
    return (Byte, Nothing, t)
-}
desugarFieldP :: P.Field -> De (Maybe Name,Pat)
desugarFieldP = \case
  P.Named (Ident nm) e -> do
    p <- desugarP e
    return (Just nm, p)
  P.Anon e -> do
    p <- desugarP e
    return (Nothing, p)
--Now struct fields need pad,alignment,mnm,e
--Niggle: even if different pad or alignment info has no effect on runtime
--repr, the types are distinct.
desugarField :: (P.E -> De a) -> P.Field -> De (Field a)
desugarField de = go Nothing Nothing
  where go mpad mal = \case
          P.AnnotPad p f
            | Just p' <- mpad -> throwE $ DuplicatePads p' $ P.AnnotPad p f
            | let -> go (toPad p) mal f
          P.AnnotAlign p f
            | Just p' <- mal -> throwE $ DuplicateAligns p' $ P.AnnotAlign p f
            | let -> go mpad (toPad p) f
          P.Named (Ident nm) e -> do
            x <- de e
            return ((deflt mpad, deflt mal), Just nm, x)
          P.Anon e -> do
            x <- de e
            return ((deflt mpad, deflt mal), Nothing, x)
        deflt = \case
          Nothing -> Byte
          Just p -> p
        toPad = Just . \case
          P.Bit -> Bit
          P.Byte -> Byte
          P.Word -> Word
{-
_, x, {p | field:p,...}, (p1,p2,...)
-}
desugarP :: P.E -> De Pat
desugarP = do
  let r = desugarP
  \case
    --Assign makes no sense
    --FW ops: !! ~ _[_]
    --FW prefix op: *_, -_
    --For now, there are no Con ps applications
    P.Var (Ident nm) -> return $ PVar nm
    --For now, no Con patterns
    --Dot makes sense, but unsupported for now
    --FW: integer constants
    P.EmptyTup -> return $ PTup []
    P.Tup e es -> PTup <$> ((:) <$> r e <*> mapM r es)
    P.EmptyStruct -> return $ PStruct []
    P.EStruct fields -> PStruct <$> mapM desugarFieldP fields
    P.Wild -> return PWild
    P.Dot p (Ident field) -> PDot <$> r p <*> return field
    P.Hash p n -> PHash <$> r p <*> return (fromInteger n)
    P.PrefixOp (Infix "*") e -> Deref <$> desugarE e
    e -> throwE $ BadEInPat e

--DTs.S currently has no concept of standalone do blocks...
desugarBlock :: P.S -> De [S]
desugarBlock =
  \case P.Do ss -> mapM desugarS ss
        s -> (:[]) <$> desugarS s
desugarS :: P.S -> De S
desugarS = \case
  P.SE (P.Assign lhs rhs) -> (:=) <$> desugarP lhs <*> desugarE rhs
  P.SE e -> (PWild :=) <$> desugarE e
  P.If e th el -> Ifte <$> desugarE e <*> desugarBlock th <*> desugarBlock el
  P.While e body -> While <$> desugarE e <*> desugarBlock body
  P.Return e -> Return <$> desugarE e
  P.Do [s] -> desugarS s
  --TODO allow standalone do blocks and do expressions
  P.Do ss -> throwE $ BadDoInDesugarS ss

desugarE :: P.E -> De E
desugarE = do
  let r = desugarE
  \case
    --Assign is not an expr, but should it be...?
    --Pro: that's what C does; it gives you neat puns
    --Con: it's not a higher-level description of an existing EVM pattern, but
    --rather a C feature imposed on the EVM;
    --side effects not as explicit
    P.Assign l r -> throwE $ AssignIsNotAnE l r
    --Special handling of e :: t, the coercion operator
    --No handling of e :: t1 :: t2 for now
    --(::) mixed with other operators => parse failure
    P.Ops e (Infix "::") (OSNil te) ->
      Coerce <$> desugarT te <*> desugarE e
    P.Ops _ (Infix op) os
      | let os2ops (OSNil _) = []
            os2ops (OSCons _ (Infix op) os) = op:os2ops os,
        "::" `elem` (op:os2ops os) -> throwE $ CoerceMixedWithOps (op:os2ops os)
    --For now, use constant fixity info. FW: gather and process fixity decls
    --before desugaring Es.
    P.Ops e (Infix op) os -> do
      e1 <- r e
      opes <- desugarOpsE op os
      return $ opsToApps opPrecedenceInfo e1 opes
    --Hack: BNFC doesn't like adding a hexadecimal number token, so I'll
    --use hex("deadbeef") instead
    P.App (P.Var (Ident "hex")) (P.Str str) ->
     EInteger <$> (case readMaybe $ "0x"++str of
                      Just n -> return n
                      Nothing -> throwE $ GenericDError $
                        "Couldn't read hex number in hex(...): " ++ show str)
    P.App f x -> (:$) <$> r f <*> r x
    P.Var (Ident x) -> return $ Var x
    P.Con (UIdent x) -> return $ Var x --a name's a name to the IR
    P.Dot e (Ident f) -> (:.) <$> r e <*> return f
    P.Hash e n -> (:#) <$> r e <*> return (fromInteger n)
    P.Int n -> return $ EInteger n
    P.Str str -> return $ EString str
    P.EmptyTup -> return $ EStruct []
    P.Tup e es -> tupleE <$> ((:) <$> r e <*> mapM r es)
    P.EmptyStruct -> return $ EStruct []
    P.EStruct fields -> EStruct <$> mapM desugarFieldE fields
    --Prefix ops: * & ! ~ -
    P.PrefixOp (Infix nm) e
      | "*" <- nm ->
       (Var "deref" :$) <$> desugarE e

desugarOpsE op = \case
  OSNil e -> do
    x <- desugarE e
    return [(op,x)]
  OSCons e (Infix op') os -> do
    x <- desugarE e
    opes <- desugarOpsE op' os
    return $ (op,x) : opes

--True: binds left. Lower number: higher binding strength.
type PrecInfo = (Bool,Int)
opPrecedenceInfo = M.fromList [
  ("+",(False,6)),
  ("-",(False,6)),
  ("*",(False,5)),
  ("/",(False,5))
                              ]
defaultPrecInfo = (True,10)
--o1 `gtPrec` o2 iff o1 has a lower number or an equal number & o2 binds left
gtPrec :: PrecInfo -> PrecInfo -> Bool
gtPrec (l1,b1) (l2,b2) = b1 < b2 || (b1 == b2 && l2)
--Given a sequence e op e op ... e, converts it to a tree of applications.
--e op e1 OP e2 OP e3 ... if OP binds left e1 may be nested arbitrarily deep.
--a op b OP c ... => a op (...
opsToApps :: Map Name PrecInfo -> E -> [(Name,E)] -> E
opsToApps m e opes = shunt [e] [] opes
  --Shunting yard algo
  --An E can always be constructed since there's no mismatch between #es & #ops
  --Quirk: unlike Haskell's op prec parsing, never fails
  where shunt es ops [] = buildOps es ops
        shunt (b:a:es) (op':ops') ((op,e):opes)
          | op' >? op = shunt (appOp op' a b : es) ops' ((op,e):opes)
        shunt es ops ((op,e):opes) = shunt (e:es) (op:ops) opes
        o1 >? o2 = pinfo o1 `gtPrec` pinfo o2
        pinfo op = case M.lookup op m of
                     Just i -> i
                     Nothing -> defaultPrecInfo
        buildOps [e] [] = e
        buildOps (b:a:es) (op:ops) =
          buildOps (appOp op a b : es) ops
        appOp op a b = Var op :$ tupleE [a,b]
