{-# LANGUAGE LambdaCase #-}
module Compiler where

--Imports the modules for each step, handles running the pipeline

--String -> CST
--Generated by BNFC
import E.Par (pM,myLexer)
import E.ErrM (Err(..))
import E.Abs (Ident(..),UIdent(..),Infix(..),OS(..),Field(..))
import qualified E.Abs as P
--CST -> AST
import DTs
import Data.Map (Map(..))
import qualified Data.Map as M
--Desugaring code written in Compiler... maybe todo move
--AST -> IR
import IR1 hiding (Ifte,While,Return)
--IR -> CFG (non-stack aware)
--TODO rename...
import ToyCFG
--CFG2 -> Asm
import Stack
--Asm -> Bytecode
import Asm (Asm(..),AsmError(..),assemble,toExe)
import Data.Set (Set(..))
import qualified Data.Set as S
--For debugging:
import Pretty


--Hopefully no longer relevant, but keeping just in case:
{-
--Testing to find weird bug - for function body do {y = 1; return 2}
--the opt2 doesn't remove the garbage op.
testPrune =
  let Right cfg2m =
        pipeline2CFG2 $
        "module {f : Int Unsigned 256 -> Int Unsigned 256;" ++
        " f x := do {y = 1;return 2}}"
      Just (start,cfg2) = M.lookup "f" cfg2m
      Just slc2 = M.lookup start cfg2
      (slc,v,s,rc) = slc2
      rets = S.fromList $ let BReturn rs = slcBranch slc in rs
      ops' = pruneDeadOps (slcOps slc) rets
      --pruneDeadOps can remove it! But opt2Pass doesn't...
      cfg2' = opt2Pass start cfg2
  in (start,cfg2) --(ops',slcOps slc,cfg2' == cfg2)
--Bit of a hack to persist badly pruned module
getBadPruning :: IO (Map Name (Label,CFG2))
getBadPruning = read <$> readFile "badPruningCFG2M.txt"
-}

printIRM :: String -> IO ()
printIRM str =
  case pipeline2IR str of
    Right irm -> mapM_ putStrLn $ prettyIRM irm
    Left err -> putStrLn $ "Error: " ++ show err
--TODO dedup...
printCFG :: String -> IO ()
printCFG str =
  case pipeline2CFG str of
    Right cfgm -> mapM_ putStrLn $ showCFGM cfgm
    Left err -> putStrLn $ "Error: " ++ show err
--Doesn't display the version count or substitution maps.
printCFG2 :: String -> IO ()
printCFG2 str =
  case pipeline2CFG2 str of
    Right cfg2m -> mapM_ putStrLn $ showCFG2M cfg2m
    Left err -> putStrLn $ "Error: " ++ show err
printAsm str =
  case pipeline2Asm str of
    Right asms -> mapM_ (putStrLn . prettyAsm) asms
    Left err -> putStrLn $ "Error: " ++ show err

--Putting it all together (in progress):
data CompilerError = ParserError String
                   | DesugarError DError
                   | SeqError SeqError
                   | IllFormedCFG Name [IR]
                   | AsmError String
                   | BytecodeError AsmError
  deriving (Eq,Ord,Read,Show)
--The string set is a warning of undefined labels; none should exist
pipeline2Bytecode :: String -> Either CompilerError (Set String, [Int])
pipeline2Bytecode str = do
  asm <- pipeline2Asm str
  objectFile <- assemble asm ? BytecodeError
  return $ toExe objectFile
pipeline2Asm :: String -> Either CompilerError [Asm]
pipeline2Asm str = do
  cfg2m <- pipeline2CFG2 str
  compile2asm cfg2m ? AsmError
pipeline2CFG2 :: String ->
                 Either CompilerError (Map Name (Arity,(Label, CFG2)))
pipeline2CFG2 str = do
  cfgm <- pipeline2CFG str
  let cfg2m = M.map (\(arity,((lab,_live),cfgs)) ->
                          let cfg = labelSLCMap cfgs
                              (_,cfg') = processCFG (lab,cfg)
                          in (arity,(lab, opt2 lab cfg')))
                 cfgm
  return cfg2m
--The CFG logic doesn't care about arity, so it can be passed through the
--CFG and CFG2 steps unchanged
pipeline2CFG :: String -> Either CompilerError (Map Name (Arity,(LL,CFGS)))
pipeline2CFG str = do
  irm <- pipeline2IR str
  let ds = M.toList $ irDefuns irm
  fcfgs <- mapM (\(f,(arity,irs)) ->
                   case ir2cfg irs of
                     (Just ll, cfgs) -> return (f,(arity,(ll,cfgs)))
                     _ -> Left $ IllFormedCFG f irs) ds
  return $ M.fromList fcfgs
  
--Compiles all the way to structured IR
pipeline2IR :: String -> Either CompilerError IRModule
pipeline2IR str = do
  m <- parseModule str ? ParserError
  mod <- desugar m ? DesugarError
  irmod <- seqModule mod ? SeqError
  return irmod
  --I need to generate IR for each function called from main
  --Seq only handles a single function's IR codegen

(?) :: Either localErr a -> (localErr -> globalErr) -> Either globalErr a
Right b ? _ = Right b
Left err ? errt = Left $ errt err
--Parse a module from string
parseModule :: String -> Either String P.M
parseModule str =
  case pM $ myLexer str of
    Ok mod -> Right mod
    Bad errStr -> Left errStr

data DError = TySigDefunMismatch Name Name
            | DuplicateDefun Name
            | BadDOrdering [P.D]
            | BadOpInType String
            | BadEInType P.E --catch-all error for desugarT
            | BadEInPat P.E --same for desugarP
            | BadDoInDesugarS [P.S]
            | AssignIsNotAnE P.E P.E --for now
  deriving (Eq,Ord,Read,Show)
desugar :: P.M -> Either DError Module
desugar (P.Module ds) =
  Module <$> desugarDs M.empty ds
--Currently DT.Module only has defuns; P.M only has tysig and defun.
--Every defun f must be preceded by a tysig f : t; together they become one
--DT.Defun.
--Duplicate defuns are an error.
type De = Either DError
desugarDs :: Map Name D -> [P.D] -> De (Map Name D)
desugarDs m [] = return m
desugarDs m (P.TySig (Ident f) t :
             P.Defun (Ident f') lhs s :
             rest)
  | f /= f' = Left $ TySigDefunMismatch f f'
  | Just d <- M.lookup f m = Left $ DuplicateDefun f
  | let = do
          t' <- desugarT t
          --Note patterns are a subset of syntactically valid Es
          p <- desugarP lhs
          --Need to add do block support to DTs?
          block <- desugarBlock s
          let def = Defun f t' p block
          desugarDs (M.insert f def m) rest
desugarDs m other = Left $ BadDOrdering other

{-
type SInt = Int Signed
type UInt = Int Unsigned
T ::= Int signedness n
    | T -> T --only op allowed
    | {(T | field:T),...}
FW: Ptr, unparam'd user types
-}
desugarT :: P.E -> De T
desugarT = do
  let r = desugarT
  \case
    --Assign makes no sense in type context
    P.Ops a (Infix "->") os -> do
      at <- r a
      bst <- desugarArrowOps os
      return $ foldr1 (\a b -> a :-> b) $ at:bst
    --There are no type-level prefix ops
    P.App e1 e2 -> (:$$) <$> r e1 <*> r e2
    --No type vars for now
    P.Con (UIdent nm) -> return $ TyCon nm
    --No dot
    P.Int n -> return $ TyNat n
    P.EmptyTup -> return $ tupleT []
    P.Tup e es -> tupleT <$> ((:) <$> r e <*> mapM r es)
    P.EmptyStruct -> return $ Struct []
    P.EStruct fields -> Struct <$> mapM desugarFieldT fields
    --No wild
    e -> Left $ BadEInType e

desugarArrowOps = \case
  OSNil a -> (:[]) <$> desugarT a
  OSCons a (Infix "->") os -> do
    at <- desugarT a
    bst <- desugarArrowOps os
    return $ at : bst
  OSCons a (Infix inf) os -> Left $ BadOpInType inf
--TODO add padding keywords to syntax; for now bytepad default is mandatory
desugarFieldT :: Field -> De (Padding,Maybe Name,T)
desugarFieldT = \case
  Named (Ident nm) e -> do
    t <- desugarT e
    return (BytePad, Just nm, t)
  Anon e -> do
    t <- desugarT e
    return (BytePad, Nothing, t)
desugarFieldP :: Field -> De (Maybe Name,Pat)
desugarFieldP = \case
  Named (Ident nm) e -> do
    p <- desugarP e
    return (Just nm, p)
  Anon e -> do
    p <- desugarP e
    return (Nothing, p)
desugarFieldE :: Field -> De (Padding, Maybe Name, E)
desugarFieldE = \case
  Named (Ident nm) e -> do
    x <- desugarE e
    return (BytePad, Just nm, x)
  Anon e -> do
    x <- desugarE e
    return (BytePad, Nothing, x)
{-
_, x, {p | field:p,...}, (p1,p2,...)
-}
desugarP :: P.E -> De Pat
desugarP = do
  let r = desugarP
  \case
    --Assign makes no sense
    --FW ops: !! ~ _[_]
    --FW prefix op: *_, -_
    --For now, there are no Con ps applications
    P.Var (Ident nm) -> return $ PVar nm
    --For now, no Con patterns
    --Dot makes sense, but unsupported for now
    --FW: integer constants
    P.EmptyTup -> return $ PTup []
    P.Tup e es -> PTup <$> ((:) <$> r e <*> mapM r es)
    P.EmptyStruct -> return $ PStruct []
    P.EStruct fields -> PStruct <$> mapM desugarFieldP fields
    P.Wild -> return PWild
    e -> Left $ BadEInPat e

--DTs.S currently has no concept of standalone do blocks...
desugarBlock :: P.S -> De [S]
desugarBlock =
  \case P.Do ss -> mapM desugarS ss
        s -> (:[]) <$> desugarS s
desugarS :: P.S -> De S
desugarS = \case
  P.SE (P.Assign lhs rhs) -> (:=) <$> desugarP lhs <*> desugarE rhs
  P.SE e -> (PWild :=) <$> desugarE e
  P.If e th el -> Ifte <$> desugarE e <*> desugarBlock th <*> desugarBlock el
  P.While e body -> While <$> desugarE e <*> desugarBlock body
  P.Return e -> Return <$> desugarE e
  P.Do [s] -> desugarS s
  --TODO allow standalone do blocks and do expressions
  P.Do ss -> Left $ BadDoInDesugarS ss

desugarE :: P.E -> De E
desugarE = do
  let r = desugarE
  \case
    --Assign is not an expr, but should it be...?
    --Pro: that's what C does; it gives you neat puns
    --Con: it's not a higher-level description of an existing EVM pattern, but
    --rather a C feature imposed on the EVM;
    --side effects not as explicit
    P.Assign l r -> Left $ AssignIsNotAnE l r
    --For now, use constant fixity info. FW: gather and process fixity decls
    --before desugaring Es.
    P.Ops e (Infix op) os -> do
      e1 <- r e
      opes <- desugarOpsE op os
      return $ opsToApps opPrecedenceInfo e1 opes
    P.App f x -> (:$) <$> r f <*> r x
    P.Var (Ident x) -> return $ Var x
    P.Con (UIdent x) -> return $ Var x --a name's a name to the IR
    P.Dot e (Ident f) -> error "TODO support dot in DTs.E"
    P.Int n -> return $ EInteger n
    P.EmptyTup -> return $ EStruct []
    P.Tup e es -> tupleE <$> ((:) <$> r e <*> mapM r es)
    P.EmptyStruct -> return $ EStruct []
    P.EStruct fields -> EStruct <$> mapM desugarFieldE fields

desugarOpsE op = \case
  OSNil e -> do
    x <- desugarE e
    return [(op,x)]
  OSCons e (Infix op') os -> do
    x <- desugarE e
    opes <- desugarOpsE op' os
    return $ (op,x) : opes

--True: binds left. Lower number: higher binding strength.
type PrecInfo = (Bool,Int)
opPrecedenceInfo = M.fromList [
  ("+",(False,6)),
  ("-",(False,6)),
  ("*",(False,5)),
  ("/",(False,5))
                              ]
defaultPrecInfo = (True,10)
--o1 `gtPrec` o2 iff o1 has a lower number or an equal number & o2 binds left
gtPrec :: PrecInfo -> PrecInfo -> Bool
gtPrec (l1,b1) (l2,b2) = b1 < b2 || (b1 == b2 && l2)
--Given a sequence e op e op ... e, converts it to a tree of applications.
--e op e1 OP e2 OP e3 ... if OP binds left e1 may be nested arbitrarily deep.
--a op b OP c ... => a op (...
opsToApps :: Map Name PrecInfo -> E -> [(Name,E)] -> E
opsToApps m e opes = shunt [e] [] opes
  --Shunting yard algo
  --An E can always be constructed since there's no mismatch between #es & #ops
  --Quirk: unlike Haskell's op prec parsing, never fails
  where shunt es ops [] = buildOps es ops
        shunt (b:a:es) (op':ops') ((op,e):opes)
          | op' >? op = shunt (appOp op' a b : es) ops' ((op,e):opes)
        shunt es ops ((op,e):opes) = shunt (e:es) (op:ops) opes
        o1 >? o2 = pinfo o1 `gtPrec` pinfo o2
        pinfo op = case M.lookup op m of
                     Just i -> i
                     Nothing -> defaultPrecInfo
        buildOps [e] [] = e
        buildOps (b:a:es) (op:ops) =
          buildOps (appOp op a b : es) ops
        appOp op a b = Var op :$ tupleE [a,b]
