cabal-version:       2.4
name:                evmc
version:             0.1.0.0
build-type:          Custom
extra-source-files:
        Stdlib/Alloc.evmc
        Stdlib/Arith.evmc
        Stdlib/Defaults.evmc
        Stdlib/EVM.evmc
        Stdlib/Kinds.evmc
        Stdlib/Prelude.evmc
        Stdlib/Terminate.evmc
        Stdlib/Types.evmc
        Stdlib/TySyns.evmc
        Stdlib/Test/ArrayInterpreter.evmc
        Stdlib/Test/ArrowOp.evmc
        Stdlib/Test/ArrowOpNoNestedCall.evmc
        Stdlib/Test/CallInPtrAssignmentWorks.evmc
        Stdlib/Test/ContractCreation.evmc
        Stdlib/Test/EfficientHello.evmc
        Stdlib/Test/EvaluatedPat.evmc
        Stdlib/Test/GlobalArrayIndex.evmc
        Stdlib/Test/HelloWorld.evmc
        Stdlib/Test/Offset.evmc
        Stdlib/Test/Shadowing.evmc
        Stdlib/Test/ShiftedLabel.evmc
        Stdlib/Test/ShiftedLabel2.evmc
        Stdlib/Test/Shrinking.evmc
        Stdlib/Test/WordPadOffset.evmc
--formerly Simple
custom-setup
   setup-depends:       base
                      , Cabal
                      , BNFC >= 2.9                        
                      , process
                      , directory
library
  exposed-modules:     Compiler
  other-modules: AST.DTs
               , AST.Util
               , Desugar.DTs
               , Desugar.Datatypes
               , Desugar.Desugar
               , Desugar.SEP
               , Desugar.T
               , Desugar.Util
               , E.Abs
               , E.ErrM
               , E.Lex
               , E.Par
               , Mono.Mono
               , Parse
               , Stdlib.ImplicitImports
               , Typecheck.DependencyGraph
               , Typecheck.FIKS
               , Typecheck.HM
               , Typecheck.HM.AddConsAndFieldsToTySigs
               , Typecheck.TC
               , Typecheck.TySyn
               , Util
               --Adding because install complains they're missing:
               , Import
               , DeclBucket
               , Unshadow.Unshadow
               , Structured.DTs
               , Fused.Monad
               , Fused
               , Core.RestrictedCore
               , Core.Convert
               , Core.SSA
               , Opt.AI
               , Opt.Opt
               , Codegen
               , Asm
               , Pretty
               , Opt.AI.Test
               , Opcodes
               , Const.Const
               , Core.PrimTypes
               , Opt.Concurrent
               , Opt.AbVar
               , Opt.Semilattice
               , Opt.HTraversable
               , Opt.AI.EVM
               , Opt.CodeG2Labels
               , Construct
               , OpcodeInfo
               , Opt.Analysis.Exitness
               , Opt.CC
               , Opt.Peephole
  --Removed because they break cabal install exe:evmc
  --autogen-modules:
  --             , E.Abs
  --             , E.ErrM
  --             , E.Lex
  --             , E.Par
  hs-source-dirs:      .
  build-depends:       base ^>= 4.18
                     , syb
                     , BNFC >= 2.9
                     , containers
                     , mtl
                     , transformers ^>= 0.6.1.0
                     , template-haskell >= 2.20.0.0
                     , array >= 0.5.8.0
                     , process
                     , directory
                     -- , filepath
                     , QuickCheck
                     , wide-word
  build-tool-depends: alex:alex >= 3.2
                    , happy:happy >= 1.19
                    , BNFC:bnfc >= 2.9

  default-language:    Haskell2010
  --extra-source-files: Stdlib/Prelude.evmc
--TODO add the other stdlib files
executable evmc
  main-is: CLI.hs
  hs-source-dirs: .
  build-depends:       base ^>= 4.18
                     , evmc
                     , syb
                     , containers
                     , mtl
                     , transformers ^>= 0.6.1.0
                     , template-haskell >= 2.20.0.0
                     , array >= 0.5.8.0
                     , process
                     , directory
                     , QuickCheck
                     , wide-word
  default-language: Haskell2010
