## File generated by the BNF Converter (bnfc 2.9.6.1).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : E\Test

# Rules for building the parser.

E\Abs.hs E\Lex.x E\Par.y E\Print.hs E\Test.hs : E.cf
	bnfc --haskell -d --functor E.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

E\Test : E\Abs.hs E\Lex.hs E\Par.hs E\Print.hs E\Test.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f E\*.hi E\*.o E\*.log E\*.aux E\*.dvi

distclean : clean
	-rm -f E\Abs.hs E\Abs.hs.bak E\ComposOp.hs E\ComposOp.hs.bak E\Doc.txt E\Doc.txt.bak E\ErrM.hs E\ErrM.hs.bak E\Layout.hs E\Layout.hs.bak E\Lex.x E\Lex.x.bak E\Par.y E\Par.y.bak E\Print.hs E\Print.hs.bak E\Skel.hs E\Skel.hs.bak E\Test.hs E\Test.hs.bak E\XML.hs E\XML.hs.bak E\AST.agda E\AST.agda.bak E\Parser.agda E\Parser.agda.bak E\IOLib.agda E\IOLib.agda.bak E\Main.agda E\Main.agda.bak E\E.dtd E\E.dtd.bak E\Test E\Lex.hs E\Par.hs E\Par.info E\ParData.hs Makefile
	-rmdir -p E\

# EOF
