module Parse where
--A standalone module for the parsing (String -> CST) stage

--String -> CST
--Generated by BNFC
import E.Par (pM,myLexer,
              pModuleName)
import E.ErrM (Err(..))
--import E.Abs (Ident(..),UIdent(..),Infix(..),OS(..))
import qualified E.Abs as P

--Parse a module from string
parseModule :: String -> Either String P.M
parseModule str =
  pM $ myLexer str

--Checks whether a string is a valid UIdent (without any whitespace).
--This is a hack...
isUIdent :: String -> Bool
isUIdent str =
  case pModuleName $ myLexer str of
    Right (P.MNil _ (P.UIdent str')) -> str == str'
    _ -> False
