module Parse where
--A standalone module for the parsing (String -> CST) stage

--String -> CST
--Generated by BNFC
import E.Par (pM,myLexer)
import E.ErrM (Err(..))
--import E.Abs (Ident(..),UIdent(..),Infix(..),OS(..))
import qualified E.Abs as P

--Parse a module from string
parseModule :: String -> Either String P.M
parseModule str =
  pM $ myLexer str
