{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module UniSyn.Print where

-- pretty-printer generated by the BNF converter

import UniSyn.Abs
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))


instance Print UIdent where
  prt _ (UIdent i) = doc (showString ( i))



instance Print D where
  prt i e = case e of
    TySig id e_ -> prPrec i 0 (concatD [prt 0 id, doc (showString ":"), prt 0 e_])
    Defun id e_ ss -> prPrec i 0 (concatD [prt 0 id, prt 1 e_, doc (showString ":="), doc (showString "{"), prt 0 ss, doc (showString "}")])

instance Print S where
  prt i e = case e of
    PlaceholderS -> prPrec i 0 (concatD [doc (showString "S")])
    Assign e_1 e_2 -> prPrec i 0 (concatD [prt 1 e_1, doc (showString "="), prt 0 e_2])
    Return e_ -> prPrec i 0 (concatD [doc (showString "return"), prt 0 e_])
    If e_ s -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 e_, doc (showString ")"), prt 0 s])
    Else s -> prPrec i 0 (concatD [doc (showString "else"), prt 0 s])
    While e_ s -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 e_, doc (showString ")"), prt 0 s])
    Do ss -> prPrec i 0 (concatD [doc (showString "{"), prt 0 ss, doc (showString "}")])
  prtList _ [] = (concatD [])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ";"), prt 0 xs])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ";"), prt 0 xs])
instance Print E where
  prt i e = case e of
    EInt n -> prPrec i 1 (concatD [prt 0 n])
    EVar id -> prPrec i 1 (concatD [prt 0 id])
    ECon uident -> prPrec i 1 (concatD [prt 0 uident])
    EEmptyTup -> prPrec i 1 (concatD [doc (showString "("), doc (showString ")")])
    ETup e_ es -> prPrec i 1 (concatD [doc (showString "("), prt 0 e_, doc (showString ","), prt 0 es, doc (showString ")")])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])

