

module E.Abs where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
newtype UIdent = UIdent String deriving (Eq, Ord, Show, Read)
newtype Infix = Infix String deriving (Eq, Ord, Show, Read)
data M = Module [D]
  deriving (Eq, Ord, Show, Read)

data D = Defun Ident E S | TestE E
  deriving (Eq, Ord, Show, Read)

data S = SE E
  deriving (Eq, Ord, Show, Read)

data EField = ENamed Ident E | EAnon E
  deriving (Eq, Ord, Show, Read)

data E
    = Struct [EField]
    | Int Integer
    | Var Ident
    | And E E
    | Or E E
    | Assign E AOp E
  deriving (Eq, Ord, Show, Read)

data AOp
    = Eq
    | PlusEq
    | MinusEq
    | MulEq
    | DivEq
    | ModEq
    | ShlEq
    | ShrEq
    | AndEq
    | XorEq
    | OrEq
  deriving (Eq, Ord, Show, Read)

data T = TVar
  deriving (Eq, Ord, Show, Read)

