-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE DeriveTraversable #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE PatternSynonyms #-}

-- | The abstract syntax of language E.

module E.Abs where

import Prelude (Integer, String)
import qualified Prelude as C
  ( Eq, Ord, Show, Read
  , Functor, Foldable, Traversable
  , Int, Maybe(..)
  )
import qualified Data.String

type M = M' BNFC'Position
data M' a = Module a [D' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type D = D' BNFC'Position
data D' a
    = Default a UIdent (T' a)
    | Defun a Ident (E' a) (S' a)
    | Instance a Ident (T' a) (E' a) (S' a)
    | TySig a Ident (T' a)
    | KindSig a UIdent (T' a)
    | TySyn a (ConArgs' a) (T' a)
    | Import a (ModuleName' a)
    | Global a (GlobalRegion' a) (VarBind' a)
    | Data a (ConArgs' a) (DataRHS' a)
    | Tag a (ConArgs' a) (T' a) [ConTag' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type ConArgs = ConArgs' BNFC'Position
data ConArgs' a = CANil a UIdent | CACons a (ConArgs' a) Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type ModuleName = ModuleName' BNFC'Position
data ModuleName' a = MNil a UIdent | MCons a UIdent (ModuleName' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type GlobalRegion = GlobalRegion' BNFC'Position
data GlobalRegion' a = Memory a | Storage a | TStorage a | Code a
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type DataRHS = DataRHS' BNFC'Position
data DataRHS' a
    = Boxed a (UnboxedRHS' a) Ident | Unboxed a (UnboxedRHS' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type UnboxedRHS = UnboxedRHS' BNFC'Position
data UnboxedRHS' a = URHS a [DataCon' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type DataCon = DataCon' BNFC'Position
data DataCon' a
    = DCArgs a (DCA' a) | DCRecord a UIdent [RecordField' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type DCA = DCA' BNFC'Position
data DCA' a = DCANil a UIdent | DCACons a (DCA' a) (T' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type RecordField = RecordField' BNFC'Position
data RecordField' a = RF a Ident (T' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type ConTag = ConTag' BNFC'Position
data ConTag' a = ConTag a UIdent (E' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type S = S' BNFC'Position
data S' a
    = SE a (E' a)
    | If a (E' a) (S' a) (S' a)
    | While a (E' a) (S' a)
    | Return a (E' a)
    | Do a [S' a]
    | Case a (E' a) [CASE' a]
    | Break a
    | Continue a
    | For a (S' a) (E' a) (S' a) (S' a)
    | Declare a [VarBind' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type CASE = CASE' BNFC'Position
data CASE' a = C a (E' a) (S' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type VarBind = VarBind' BNFC'Position
data VarBind' a = JustVar a Ident | VarIs a Ident (E' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type E = E' BNFC'Position
data E' a
    = EmptyTuple a
    | Tuple a (E' a) [E' a]
    | HexInt a HexInteger
    | Int a Integer
    | Var a Ident
    | String a String
    | ConRecord a UIdent [EField' a]
    | Con a UIdent
    | Wild a
    | PlusPlusPost a (E' a)
    | MinusMinusPost a (E' a)
    | Index a (E' a) (E' a)
    | Dot a (E' a) Ident
    | Bang a (E' a) (E' a)
    | Arrow a (E' a) Ident
    | App a (E' a) (E' a)
    | PlusPlusPre a (E' a)
    | MinusMinusPre a (E' a)
    | Negate a (E' a)
    | Not a (E' a)
    | BitwiseNot a (E' a)
    | Deref a (E' a)
    | AddressOf a (E' a)
    | Mul a (E' a) (E' a)
    | Div a (E' a) (E' a)
    | Mod a (E' a) (E' a)
    | Plus a (E' a) (E' a)
    | Minus a (E' a) (E' a)
    | Shl a (E' a) (E' a)
    | Shr a (E' a) (E' a)
    | MyLT a (E' a) (E' a)
    | LTE a (E' a) (E' a)
    | MyGT a (E' a) (E' a)
    | GTE a (E' a) (E' a)
    | Eq a (E' a) (E' a)
    | NEq a (E' a) (E' a)
    | BitwiseAnd a (E' a) (E' a)
    | BitwiseXor a (E' a) (E' a)
    | BitwiseOr a (E' a) (E' a)
    | And a (E' a) (E' a)
    | Or a (E' a) (E' a)
    | Assign a (E' a) (AOp' a) (E' a)
    | TypeAnnot a (E' a) (T' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type EField = EField' BNFC'Position
data EField' a = EField a Ident (E' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type AOp = AOp' BNFC'Position
data AOp' a
    = EqEq a
    | PlusEq a
    | MinusEq a
    | MulEq a
    | DivEq a
    | ModEq a
    | ShlEq a
    | ShrEq a
    | AndEq a
    | XorEq a
    | OrEq a
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type T = T' BNFC'Position
data T' a
    = TArrow a (T' a) (T' a)
    | TVar a Ident
    | TNat a Integer
    | TCon a UIdent
    | TEmptyTup a
    | TTup a (T' a) [T' a]
    | TApp a (T' a) (T' a)
    | TArray a (T' a) (T' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype UIdent = UIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype Infix = Infix String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype HexInteger = HexInteger String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

-- | Start position (line, column) of something.

type BNFC'Position = C.Maybe (C.Int, C.Int)

pattern BNFC'NoPosition :: BNFC'Position
pattern BNFC'NoPosition = C.Nothing

pattern BNFC'Position :: C.Int -> C.Int -> BNFC'Position
pattern BNFC'Position line col = C.Just (line, col)

-- | Get the start position of something.

class HasPosition a where
  hasPosition :: a -> BNFC'Position

instance HasPosition M where
  hasPosition = \case
    Module p _ -> p

instance HasPosition D where
  hasPosition = \case
    Default p _ _ -> p
    Defun p _ _ _ -> p
    Instance p _ _ _ _ -> p
    TySig p _ _ -> p
    KindSig p _ _ -> p
    TySyn p _ _ -> p
    Import p _ -> p
    Global p _ _ -> p
    Data p _ _ -> p
    Tag p _ _ _ -> p

instance HasPosition ConArgs where
  hasPosition = \case
    CANil p _ -> p
    CACons p _ _ -> p

instance HasPosition ModuleName where
  hasPosition = \case
    MNil p _ -> p
    MCons p _ _ -> p

instance HasPosition GlobalRegion where
  hasPosition = \case
    Memory p -> p
    Storage p -> p
    TStorage p -> p
    Code p -> p

instance HasPosition DataRHS where
  hasPosition = \case
    Boxed p _ _ -> p
    Unboxed p _ -> p

instance HasPosition UnboxedRHS where
  hasPosition = \case
    URHS p _ -> p

instance HasPosition DataCon where
  hasPosition = \case
    DCArgs p _ -> p
    DCRecord p _ _ -> p

instance HasPosition DCA where
  hasPosition = \case
    DCANil p _ -> p
    DCACons p _ _ -> p

instance HasPosition RecordField where
  hasPosition = \case
    RF p _ _ -> p

instance HasPosition ConTag where
  hasPosition = \case
    ConTag p _ _ -> p

instance HasPosition S where
  hasPosition = \case
    SE p _ -> p
    If p _ _ _ -> p
    While p _ _ -> p
    Return p _ -> p
    Do p _ -> p
    Case p _ _ -> p
    Break p -> p
    Continue p -> p
    For p _ _ _ _ -> p
    Declare p _ -> p

instance HasPosition CASE where
  hasPosition = \case
    C p _ _ -> p

instance HasPosition VarBind where
  hasPosition = \case
    JustVar p _ -> p
    VarIs p _ _ -> p

instance HasPosition E where
  hasPosition = \case
    EmptyTuple p -> p
    Tuple p _ _ -> p
    HexInt p _ -> p
    Int p _ -> p
    Var p _ -> p
    String p _ -> p
    ConRecord p _ _ -> p
    Con p _ -> p
    Wild p -> p
    PlusPlusPost p _ -> p
    MinusMinusPost p _ -> p
    Index p _ _ -> p
    Dot p _ _ -> p
    Bang p _ _ -> p
    Arrow p _ _ -> p
    App p _ _ -> p
    PlusPlusPre p _ -> p
    MinusMinusPre p _ -> p
    Negate p _ -> p
    Not p _ -> p
    BitwiseNot p _ -> p
    Deref p _ -> p
    AddressOf p _ -> p
    Mul p _ _ -> p
    Div p _ _ -> p
    Mod p _ _ -> p
    Plus p _ _ -> p
    Minus p _ _ -> p
    Shl p _ _ -> p
    Shr p _ _ -> p
    MyLT p _ _ -> p
    LTE p _ _ -> p
    MyGT p _ _ -> p
    GTE p _ _ -> p
    Eq p _ _ -> p
    NEq p _ _ -> p
    BitwiseAnd p _ _ -> p
    BitwiseXor p _ _ -> p
    BitwiseOr p _ _ -> p
    And p _ _ -> p
    Or p _ _ -> p
    Assign p _ _ _ -> p
    TypeAnnot p _ _ -> p

instance HasPosition EField where
  hasPosition = \case
    EField p _ _ -> p

instance HasPosition AOp where
  hasPosition = \case
    EqEq p -> p
    PlusEq p -> p
    MinusEq p -> p
    MulEq p -> p
    DivEq p -> p
    ModEq p -> p
    ShlEq p -> p
    ShrEq p -> p
    AndEq p -> p
    XorEq p -> p
    OrEq p -> p

instance HasPosition T where
  hasPosition = \case
    TArrow p _ _ -> p
    TVar p _ -> p
    TNat p _ -> p
    TCon p _ -> p
    TEmptyTup p -> p
    TTup p _ _ -> p
    TApp p _ _ -> p
    TArray p _ _ -> p

