

module E.Abs where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
newtype UIdent = UIdent String deriving (Eq, Ord, Show, Read)
newtype Infix = Infix String deriving (Eq, Ord, Show, Read)
data M = Module [D]
  deriving (Eq, Ord, Show, Read)

data D = Defun Ident E S | TySig Ident E | TySyn ConArgs E
  deriving (Eq, Ord, Show, Read)

data ConArgs = CANil UIdent | CACons ConArgs Ident
  deriving (Eq, Ord, Show, Read)

data S = SE E | If E S S | While E S | Return E | Do [S]
  deriving (Eq, Ord, Show, Read)

data E
    = Assign E E
    | Ops E Infix OS
    | PrefixOp Infix E
    | App E E
    | Var Ident
    | Con UIdent
    | Dot E Ident
    | Int Integer
    | EmptyTup
    | Tup E [E]
    | EmptyStruct
    | EStruct [Field]
    | Wild
  deriving (Eq, Ord, Show, Read)

data OS = OSNil E | OSCons E Infix OS
  deriving (Eq, Ord, Show, Read)

data Field
    = AnnotPad PadInfo Field
    | AnnotAlign PadInfo Field
    | Named Ident E
    | Anon E
  deriving (Eq, Ord, Show, Read)

data PadInfo = Bit | Byte | Word
  deriving (Eq, Ord, Show, Read)

