-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.6.3).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -Wno-incomplete-patterns -Wno-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module E.Par
  ( happyError
  , myLexer
  , pM
  , pListD
  , pD
  , pConArgs
  , pModuleName
  , pGlobalRegion
  , pDataRHS
  , pUnboxedRHS
  , pListDataCon
  , pDataCon
  , pDCA
  , pListRecordField
  , pRecordField
  , pListConTag
  , pConTag
  , pS
  , pListS
  , pListCASE
  , pCASE
  , pListVarBind
  , pVarBind
  , pE13
  , pListE
  , pListEField
  , pEField
  , pE12
  , pE11
  , pE10
  , pE9
  , pE8
  , pE7
  , pE6
  , pE5
  , pE4
  , pE3
  , pE2
  , pE1
  , pE
  , pAOp
  , pT
  , pT2
  , pListT
  , pT1
  ) where

import Prelude

import qualified E.Abs
import E.Lex

}

%name pM_internal M
%name pListD_internal ListD
%name pD_internal D
%name pConArgs_internal ConArgs
%name pModuleName_internal ModuleName
%name pGlobalRegion_internal GlobalRegion
%name pDataRHS_internal DataRHS
%name pUnboxedRHS_internal UnboxedRHS
%name pListDataCon_internal ListDataCon
%name pDataCon_internal DataCon
%name pDCA_internal DCA
%name pListRecordField_internal ListRecordField
%name pRecordField_internal RecordField
%name pListConTag_internal ListConTag
%name pConTag_internal ConTag
%name pS_internal S
%name pListS_internal ListS
%name pListCASE_internal ListCASE
%name pCASE_internal CASE
%name pListVarBind_internal ListVarBind
%name pVarBind_internal VarBind
%name pE13_internal E13
%name pListE_internal ListE
%name pListEField_internal ListEField
%name pEField_internal EField
%name pE12_internal E12
%name pE11_internal E11
%name pE10_internal E10
%name pE9_internal E9
%name pE8_internal E8
%name pE7_internal E7
%name pE6_internal E6
%name pE5_internal E5
%name pE4_internal E4
%name pE3_internal E3
%name pE2_internal E2
%name pE1_internal E1
%name pE_internal E
%name pAOp_internal AOp
%name pT_internal T
%name pT2_internal T2
%name pListT_internal ListT
%name pT1_internal T1
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '!'          { PT _ (TS _ 1)         }
  '!='         { PT _ (TS _ 2)         }
  '%'          { PT _ (TS _ 3)         }
  '%='         { PT _ (TS _ 4)         }
  '&'          { PT _ (TS _ 5)         }
  '&&'         { PT _ (TS _ 6)         }
  '&='         { PT _ (TS _ 7)         }
  '('          { PT _ (TS _ 8)         }
  ')'          { PT _ (TS _ 9)         }
  '*'          { PT _ (TS _ 10)        }
  '*='         { PT _ (TS _ 11)        }
  '+'          { PT _ (TS _ 12)        }
  '++'         { PT _ (TS _ 13)        }
  '+='         { PT _ (TS _ 14)        }
  ','          { PT _ (TS _ 15)        }
  '-'          { PT _ (TS _ 16)        }
  '--'         { PT _ (TS _ 17)        }
  '-='         { PT _ (TS _ 18)        }
  '->'         { PT _ (TS _ 19)        }
  '.'          { PT _ (TS _ 20)        }
  '/'          { PT _ (TS _ 21)        }
  '/='         { PT _ (TS _ 22)        }
  ':'          { PT _ (TS _ 23)        }
  '::'         { PT _ (TS _ 24)        }
  ':='         { PT _ (TS _ 25)        }
  ';'          { PT _ (TS _ 26)        }
  '<'          { PT _ (TS _ 27)        }
  '<<'         { PT _ (TS _ 28)        }
  '<<='        { PT _ (TS _ 29)        }
  '<='         { PT _ (TS _ 30)        }
  '='          { PT _ (TS _ 31)        }
  '=='         { PT _ (TS _ 32)        }
  '=>'         { PT _ (TS _ 33)        }
  '>'          { PT _ (TS _ 34)        }
  '>='         { PT _ (TS _ 35)        }
  '>>'         { PT _ (TS _ 36)        }
  '>>='        { PT _ (TS _ 37)        }
  '['          { PT _ (TS _ 38)        }
  ']'          { PT _ (TS _ 39)        }
  '^'          { PT _ (TS _ 40)        }
  '^='         { PT _ (TS _ 41)        }
  '_'          { PT _ (TS _ 42)        }
  'break'      { PT _ (TS _ 43)        }
  'case'       { PT _ (TS _ 44)        }
  'code'       { PT _ (TS _ 45)        }
  'continue'   { PT _ (TS _ 46)        }
  'contract'   { PT _ (TS _ 47)        }
  'data'       { PT _ (TS _ 48)        }
  'default'    { PT _ (TS _ 49)        }
  'else'       { PT _ (TS _ 50)        }
  'end'        { PT _ (TS _ 51)        }
  'for'        { PT _ (TS _ 52)        }
  'if'         { PT _ (TS _ 53)        }
  'import'     { PT _ (TS _ 54)        }
  'instance'   { PT _ (TS _ 55)        }
  'memory'     { PT _ (TS _ 56)        }
  'of'         { PT _ (TS _ 57)        }
  'region'     { PT _ (TS _ 58)        }
  'return'     { PT _ (TS _ 59)        }
  'storage'    { PT _ (TS _ 60)        }
  'tag'        { PT _ (TS _ 61)        }
  'then'       { PT _ (TS _ 62)        }
  'tstorage'   { PT _ (TS _ 63)        }
  'type'       { PT _ (TS _ 64)        }
  'var'        { PT _ (TS _ 65)        }
  'where'      { PT _ (TS _ 66)        }
  'while'      { PT _ (TS _ 67)        }
  '{'          { PT _ (TS _ 68)        }
  '|'          { PT _ (TS _ 69)        }
  '|='         { PT _ (TS _ 70)        }
  '||'         { PT _ (TS _ 71)        }
  '}'          { PT _ (TS _ 72)        }
  '~'          { PT _ (TS _ 73)        }
  L_Ident      { PT _ (TV _)           }
  L_integ      { PT _ (TI _)           }
  L_quoted     { PT _ (TL _)           }
  L_UIdent     { PT _ (T_UIdent _)     }
  L_Infix      { PT _ (T_Infix _)      }
  L_HexInteger { PT _ (T_HexInteger _) }

%%

Ident :: { (E.Abs.BNFC'Position, E.Abs.Ident) }
Ident  : L_Ident { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Ident (tokenText $1)) }

Integer :: { (E.Abs.BNFC'Position, Integer) }
Integer  : L_integ  { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), (read (tokenText $1)) :: Integer) }

String  :: { (E.Abs.BNFC'Position, String) }
String   : L_quoted { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), ((\(PT _ (TL s)) -> s) $1)) }

UIdent :: { (E.Abs.BNFC'Position, E.Abs.UIdent) }
UIdent  : L_UIdent { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.UIdent (tokenText $1)) }

Infix :: { (E.Abs.BNFC'Position, E.Abs.Infix) }
Infix  : L_Infix { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Infix (tokenText $1)) }

HexInteger :: { (E.Abs.BNFC'Position, E.Abs.HexInteger) }
HexInteger  : L_HexInteger { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.HexInteger (tokenText $1)) }

M :: { (E.Abs.BNFC'Position, E.Abs.M) }
M : ListD { (fst $1, E.Abs.Module (fst $1) (snd $1)) }

ListD :: { (E.Abs.BNFC'Position, [E.Abs.D]) }
ListD
  : {- empty -} { (E.Abs.BNFC'NoPosition, []) }
  | D { (fst $1, (:[]) (snd $1)) }
  | D ';' ListD { (fst $1, (:) (snd $1) (snd $3)) }

D :: { (E.Abs.BNFC'Position, E.Abs.D) }
D : 'default' UIdent '=' T { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Default (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $4)) }
  | Ident E13 ':=' S { (fst $1, E.Abs.Defun (fst $1) (snd $1) (snd $2) (snd $4)) }
  | 'instance' Ident ':' T 'where' E13 ':=' S { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Instance (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $4) (snd $6) (snd $8)) }
  | Ident ':' T { (fst $1, E.Abs.TySig (fst $1) (snd $1) (snd $3)) }
  | UIdent ':' T { (fst $1, E.Abs.KindSig (fst $1) (snd $1) (snd $3)) }
  | 'type' ConArgs '=' T { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.TySyn (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $4)) }
  | 'import' ModuleName { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Import (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2)) }
  | GlobalRegion VarBind { (fst $1, E.Abs.Global (fst $1) (snd $1) (snd $2)) }
  | 'data' ConArgs '=' DataRHS { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Data (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $4)) }
  | 'tag' ConArgs '=' T 'where' '{' ListConTag '}' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Tag (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $4) (snd $7)) }
  | 'contract' Ident '{' ListD '}' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Contract (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $4)) }

ConArgs :: { (E.Abs.BNFC'Position, E.Abs.ConArgs) }
ConArgs
  : UIdent { (fst $1, E.Abs.CANil (fst $1) (snd $1)) }
  | ConArgs Ident { (fst $1, E.Abs.CACons (fst $1) (snd $1) (snd $2)) }

ModuleName :: { (E.Abs.BNFC'Position, E.Abs.ModuleName) }
ModuleName
  : UIdent { (fst $1, E.Abs.MNil (fst $1) (snd $1)) }
  | UIdent '.' ModuleName { (fst $1, E.Abs.MCons (fst $1) (snd $1) (snd $3)) }

GlobalRegion :: { (E.Abs.BNFC'Position, E.Abs.GlobalRegion) }
GlobalRegion
  : 'memory' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Memory (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | 'storage' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Storage (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | 'tstorage' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.TStorage (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | 'code' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Code (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }

DataRHS :: { (E.Abs.BNFC'Position, E.Abs.DataRHS) }
DataRHS
  : UnboxedRHS 'region' Ident { (fst $1, E.Abs.Boxed (fst $1) (snd $1) (snd $3)) }
  | UnboxedRHS { (fst $1, E.Abs.Unboxed (fst $1) (snd $1)) }

UnboxedRHS :: { (E.Abs.BNFC'Position, E.Abs.UnboxedRHS) }
UnboxedRHS
  : '{' ListDataCon '}' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.URHS (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2)) }

ListDataCon :: { (E.Abs.BNFC'Position, [E.Abs.DataCon]) }
ListDataCon
  : {- empty -} { (E.Abs.BNFC'NoPosition, []) }
  | DataCon { (fst $1, (:[]) (snd $1)) }
  | DataCon ';' ListDataCon { (fst $1, (:) (snd $1) (snd $3)) }

DataCon :: { (E.Abs.BNFC'Position, E.Abs.DataCon) }
DataCon
  : DCA { (fst $1, E.Abs.DCArgs (fst $1) (snd $1)) }
  | UIdent '{' ListRecordField '}' { (fst $1, E.Abs.DCRecord (fst $1) (snd $1) (snd $3)) }

DCA :: { (E.Abs.BNFC'Position, E.Abs.DCA) }
DCA
  : UIdent { (fst $1, E.Abs.DCANil (fst $1) (snd $1)) }
  | DCA T2 { (fst $1, E.Abs.DCACons (fst $1) (snd $1) (snd $2)) }

ListRecordField :: { (E.Abs.BNFC'Position, [E.Abs.RecordField]) }
ListRecordField
  : {- empty -} { (E.Abs.BNFC'NoPosition, []) }
  | RecordField { (fst $1, (:[]) (snd $1)) }
  | RecordField ',' ListRecordField { (fst $1, (:) (snd $1) (snd $3)) }

RecordField :: { (E.Abs.BNFC'Position, E.Abs.RecordField) }
RecordField
  : Ident ':' T { (fst $1, E.Abs.RF (fst $1) (snd $1) (snd $3)) }

ListConTag :: { (E.Abs.BNFC'Position, [E.Abs.ConTag]) }
ListConTag
  : {- empty -} { (E.Abs.BNFC'NoPosition, []) }
  | ConTag { (fst $1, (:[]) (snd $1)) }
  | ConTag ',' ListConTag { (fst $1, (:) (snd $1) (snd $3)) }

ConTag :: { (E.Abs.BNFC'Position, E.Abs.ConTag) }
ConTag
  : UIdent ':' E { (fst $1, E.Abs.ConTag (fst $1) (snd $1) (snd $3)) }

S :: { (E.Abs.BNFC'Position, E.Abs.S) }
S : E { (fst $1, E.Abs.SE (fst $1) (snd $1)) }
  | 'if' E 'then' S 'else' S 'end' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.If (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $4) (snd $6)) }
  | 'while' '(' E ')' S { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.While (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $3) (snd $5)) }
  | 'return' E { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Return (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2)) }
  | '{' ListS '}' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Do (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2)) }
  | 'case' E 'of' '{' ListCASE '}' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Case (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $5)) }
  | 'break' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Break (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | 'continue' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Continue (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | 'for' '(' S ';' E ';' S ')' S { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.For (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $3) (snd $5) (snd $7) (snd $9)) }
  | 'var' ListVarBind { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Declare (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2)) }

ListS :: { (E.Abs.BNFC'Position, [E.Abs.S]) }
ListS
  : {- empty -} { (E.Abs.BNFC'NoPosition, []) }
  | S { (fst $1, (:[]) (snd $1)) }
  | S ';' ListS { (fst $1, (:) (snd $1) (snd $3)) }

ListCASE :: { (E.Abs.BNFC'Position, [E.Abs.CASE]) }
ListCASE
  : {- empty -} { (E.Abs.BNFC'NoPosition, []) }
  | CASE { (fst $1, (:[]) (snd $1)) }
  | CASE ';' ListCASE { (fst $1, (:) (snd $1) (snd $3)) }

CASE :: { (E.Abs.BNFC'Position, E.Abs.CASE) }
CASE : E '=>' S { (fst $1, E.Abs.C (fst $1) (snd $1) (snd $3)) }

ListVarBind :: { (E.Abs.BNFC'Position, [E.Abs.VarBind]) }
ListVarBind
  : VarBind { (fst $1, (:[]) (snd $1)) }
  | VarBind ',' ListVarBind { (fst $1, (:) (snd $1) (snd $3)) }

VarBind :: { (E.Abs.BNFC'Position, E.Abs.VarBind) }
VarBind
  : Ident { (fst $1, E.Abs.JustVar (fst $1) (snd $1)) }
  | Ident '=' E { (fst $1, E.Abs.VarIs (fst $1) (snd $1) (snd $3)) }

E13 :: { (E.Abs.BNFC'Position, E.Abs.E) }
E13
  : '(' ')' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.EmptyTuple (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | '(' E ',' ListE ')' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Tuple (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $4)) }
  | HexInteger { (fst $1, E.Abs.HexInt (fst $1) (snd $1)) }
  | Integer { (fst $1, E.Abs.Int (fst $1) (snd $1)) }
  | Ident { (fst $1, E.Abs.Var (fst $1) (snd $1)) }
  | String { (fst $1, E.Abs.String (fst $1) (snd $1)) }
  | UIdent '{' ListEField '}' { (fst $1, E.Abs.ConRecord (fst $1) (snd $1) (snd $3)) }
  | UIdent { (fst $1, E.Abs.Con (fst $1) (snd $1)) }
  | '_' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Wild (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | '(' E ')' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), (snd $2)) }

ListE :: { (E.Abs.BNFC'Position, [E.Abs.E]) }
ListE
  : E { (fst $1, (:[]) (snd $1)) }
  | E ',' ListE { (fst $1, (:) (snd $1) (snd $3)) }

ListEField :: { (E.Abs.BNFC'Position, [E.Abs.EField]) }
ListEField
  : {- empty -} { (E.Abs.BNFC'NoPosition, []) }
  | EField { (fst $1, (:[]) (snd $1)) }
  | EField ',' ListEField { (fst $1, (:) (snd $1) (snd $3)) }

EField :: { (E.Abs.BNFC'Position, E.Abs.EField) }
EField
  : Ident ':' E { (fst $1, E.Abs.EField (fst $1) (snd $1) (snd $3)) }

E12 :: { (E.Abs.BNFC'Position, E.Abs.E) }
E12
  : E12 '++' { (fst $1, E.Abs.PlusPlusPost (fst $1) (snd $1)) }
  | E12 '--' { (fst $1, E.Abs.MinusMinusPost (fst $1) (snd $1)) }
  | E12 '[' E ']' { (fst $1, E.Abs.Index (fst $1) (snd $1) (snd $3)) }
  | E12 '.' Ident { (fst $1, E.Abs.Dot (fst $1) (snd $1) (snd $3)) }
  | E12 '!' E13 { (fst $1, E.Abs.Bang (fst $1) (snd $1) (snd $3)) }
  | E12 '->' Ident { (fst $1, E.Abs.Arrow (fst $1) (snd $1) (snd $3)) }
  | E12 E13 { (fst $1, E.Abs.App (fst $1) (snd $1) (snd $2)) }
  | E13 { (fst $1, (snd $1)) }

E11 :: { (E.Abs.BNFC'Position, E.Abs.E) }
E11
  : '++' E11 { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.PlusPlusPre (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2)) }
  | '--' E11 { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.MinusMinusPre (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2)) }
  | '-' E11 { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Negate (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2)) }
  | '!' E11 { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Not (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2)) }
  | '~' E11 { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.BitwiseNot (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2)) }
  | '*' E11 { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.Deref (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2)) }
  | '&' E11 { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.AddressOf (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2)) }
  | E12 { (fst $1, (snd $1)) }

E10 :: { (E.Abs.BNFC'Position, E.Abs.E) }
E10
  : E10 '*' E11 { (fst $1, E.Abs.Mul (fst $1) (snd $1) (snd $3)) }
  | E10 '/' E11 { (fst $1, E.Abs.Div (fst $1) (snd $1) (snd $3)) }
  | E10 '%' E11 { (fst $1, E.Abs.Mod (fst $1) (snd $1) (snd $3)) }
  | E11 { (fst $1, (snd $1)) }

E9 :: { (E.Abs.BNFC'Position, E.Abs.E) }
E9
  : E9 '+' E10 { (fst $1, E.Abs.Plus (fst $1) (snd $1) (snd $3)) }
  | E9 '-' E10 { (fst $1, E.Abs.Minus (fst $1) (snd $1) (snd $3)) }
  | E10 { (fst $1, (snd $1)) }

E8 :: { (E.Abs.BNFC'Position, E.Abs.E) }
E8
  : E8 '<<' E9 { (fst $1, E.Abs.Shl (fst $1) (snd $1) (snd $3)) }
  | E8 '>>' E9 { (fst $1, E.Abs.Shr (fst $1) (snd $1) (snd $3)) }
  | E9 { (fst $1, (snd $1)) }

E7 :: { (E.Abs.BNFC'Position, E.Abs.E) }
E7
  : E7 '<' E8 { (fst $1, E.Abs.MyLT (fst $1) (snd $1) (snd $3)) }
  | E7 '<=' E8 { (fst $1, E.Abs.LTE (fst $1) (snd $1) (snd $3)) }
  | E7 '>' E8 { (fst $1, E.Abs.MyGT (fst $1) (snd $1) (snd $3)) }
  | E7 '>=' E8 { (fst $1, E.Abs.GTE (fst $1) (snd $1) (snd $3)) }
  | E8 { (fst $1, (snd $1)) }

E6 :: { (E.Abs.BNFC'Position, E.Abs.E) }
E6
  : E6 '==' E7 { (fst $1, E.Abs.Eq (fst $1) (snd $1) (snd $3)) }
  | E6 '!=' E7 { (fst $1, E.Abs.NEq (fst $1) (snd $1) (snd $3)) }
  | E7 { (fst $1, (snd $1)) }

E5 :: { (E.Abs.BNFC'Position, E.Abs.E) }
E5
  : E5 '&' E6 { (fst $1, E.Abs.BitwiseAnd (fst $1) (snd $1) (snd $3)) }
  | E6 { (fst $1, (snd $1)) }

E4 :: { (E.Abs.BNFC'Position, E.Abs.E) }
E4
  : E4 '^' E5 { (fst $1, E.Abs.BitwiseXor (fst $1) (snd $1) (snd $3)) }
  | E5 { (fst $1, (snd $1)) }

E3 :: { (E.Abs.BNFC'Position, E.Abs.E) }
E3
  : E3 '|' E4 { (fst $1, E.Abs.BitwiseOr (fst $1) (snd $1) (snd $3)) }
  | E4 { (fst $1, (snd $1)) }

E2 :: { (E.Abs.BNFC'Position, E.Abs.E) }
E2
  : E2 '&&' E3 { (fst $1, E.Abs.And (fst $1) (snd $1) (snd $3)) }
  | E3 { (fst $1, (snd $1)) }

E1 :: { (E.Abs.BNFC'Position, E.Abs.E) }
E1
  : E1 '||' E2 { (fst $1, E.Abs.Or (fst $1) (snd $1) (snd $3)) }
  | E2 { (fst $1, (snd $1)) }

E :: { (E.Abs.BNFC'Position, E.Abs.E) }
E : E1 { (fst $1, (snd $1)) }
  | E1 AOp E { (fst $1, E.Abs.Assign (fst $1) (snd $1) (snd $2) (snd $3)) }
  | E1 '::' T { (fst $1, E.Abs.TypeAnnot (fst $1) (snd $1) (snd $3)) }

AOp :: { (E.Abs.BNFC'Position, E.Abs.AOp) }
AOp
  : '=' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.EqEq (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | '+=' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.PlusEq (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | '-=' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.MinusEq (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | '*=' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.MulEq (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | '/=' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.DivEq (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | '%=' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.ModEq (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | '<<=' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.ShlEq (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | '>>=' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.ShrEq (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | '&=' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.AndEq (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | '^=' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.XorEq (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | '|=' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.OrEq (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }

T :: { (E.Abs.BNFC'Position, E.Abs.T) }
T : T1 '->' T { (fst $1, E.Abs.TArrow (fst $1) (snd $1) (snd $3)) }
  | T1 '[' T ']' { (fst $1, E.Abs.TArray (fst $1) (snd $1) (snd $3)) }
  | T1 { (fst $1, (snd $1)) }

T2 :: { (E.Abs.BNFC'Position, E.Abs.T) }
T2
  : Ident { (fst $1, E.Abs.TVar (fst $1) (snd $1)) }
  | Integer { (fst $1, E.Abs.TNat (fst $1) (snd $1)) }
  | UIdent { (fst $1, E.Abs.TCon (fst $1) (snd $1)) }
  | '(' ')' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.TEmptyTup (uncurry E.Abs.BNFC'Position (tokenLineCol $1))) }
  | '(' T ',' ListT ')' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), E.Abs.TTup (uncurry E.Abs.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $4)) }
  | '(' T ')' { (uncurry E.Abs.BNFC'Position (tokenLineCol $1), (snd $2)) }

ListT :: { (E.Abs.BNFC'Position, [E.Abs.T]) }
ListT
  : T { (fst $1, (:[]) (snd $1)) }
  | T ',' ListT { (fst $1, (:) (snd $1) (snd $3)) }

T1 :: { (E.Abs.BNFC'Position, E.Abs.T) }
T1
  : T1 T2 { (fst $1, E.Abs.TApp (fst $1) (snd $1) (snd $2)) }
  | T2 { (fst $1, (snd $1)) }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

-- Entrypoints

pM :: [Token] -> Err E.Abs.M
pM = fmap snd . pM_internal

pListD :: [Token] -> Err [E.Abs.D]
pListD = fmap snd . pListD_internal

pD :: [Token] -> Err E.Abs.D
pD = fmap snd . pD_internal

pConArgs :: [Token] -> Err E.Abs.ConArgs
pConArgs = fmap snd . pConArgs_internal

pModuleName :: [Token] -> Err E.Abs.ModuleName
pModuleName = fmap snd . pModuleName_internal

pGlobalRegion :: [Token] -> Err E.Abs.GlobalRegion
pGlobalRegion = fmap snd . pGlobalRegion_internal

pDataRHS :: [Token] -> Err E.Abs.DataRHS
pDataRHS = fmap snd . pDataRHS_internal

pUnboxedRHS :: [Token] -> Err E.Abs.UnboxedRHS
pUnboxedRHS = fmap snd . pUnboxedRHS_internal

pListDataCon :: [Token] -> Err [E.Abs.DataCon]
pListDataCon = fmap snd . pListDataCon_internal

pDataCon :: [Token] -> Err E.Abs.DataCon
pDataCon = fmap snd . pDataCon_internal

pDCA :: [Token] -> Err E.Abs.DCA
pDCA = fmap snd . pDCA_internal

pListRecordField :: [Token] -> Err [E.Abs.RecordField]
pListRecordField = fmap snd . pListRecordField_internal

pRecordField :: [Token] -> Err E.Abs.RecordField
pRecordField = fmap snd . pRecordField_internal

pListConTag :: [Token] -> Err [E.Abs.ConTag]
pListConTag = fmap snd . pListConTag_internal

pConTag :: [Token] -> Err E.Abs.ConTag
pConTag = fmap snd . pConTag_internal

pS :: [Token] -> Err E.Abs.S
pS = fmap snd . pS_internal

pListS :: [Token] -> Err [E.Abs.S]
pListS = fmap snd . pListS_internal

pListCASE :: [Token] -> Err [E.Abs.CASE]
pListCASE = fmap snd . pListCASE_internal

pCASE :: [Token] -> Err E.Abs.CASE
pCASE = fmap snd . pCASE_internal

pListVarBind :: [Token] -> Err [E.Abs.VarBind]
pListVarBind = fmap snd . pListVarBind_internal

pVarBind :: [Token] -> Err E.Abs.VarBind
pVarBind = fmap snd . pVarBind_internal

pE13 :: [Token] -> Err E.Abs.E
pE13 = fmap snd . pE13_internal

pListE :: [Token] -> Err [E.Abs.E]
pListE = fmap snd . pListE_internal

pListEField :: [Token] -> Err [E.Abs.EField]
pListEField = fmap snd . pListEField_internal

pEField :: [Token] -> Err E.Abs.EField
pEField = fmap snd . pEField_internal

pE12 :: [Token] -> Err E.Abs.E
pE12 = fmap snd . pE12_internal

pE11 :: [Token] -> Err E.Abs.E
pE11 = fmap snd . pE11_internal

pE10 :: [Token] -> Err E.Abs.E
pE10 = fmap snd . pE10_internal

pE9 :: [Token] -> Err E.Abs.E
pE9 = fmap snd . pE9_internal

pE8 :: [Token] -> Err E.Abs.E
pE8 = fmap snd . pE8_internal

pE7 :: [Token] -> Err E.Abs.E
pE7 = fmap snd . pE7_internal

pE6 :: [Token] -> Err E.Abs.E
pE6 = fmap snd . pE6_internal

pE5 :: [Token] -> Err E.Abs.E
pE5 = fmap snd . pE5_internal

pE4 :: [Token] -> Err E.Abs.E
pE4 = fmap snd . pE4_internal

pE3 :: [Token] -> Err E.Abs.E
pE3 = fmap snd . pE3_internal

pE2 :: [Token] -> Err E.Abs.E
pE2 = fmap snd . pE2_internal

pE1 :: [Token] -> Err E.Abs.E
pE1 = fmap snd . pE1_internal

pE :: [Token] -> Err E.Abs.E
pE = fmap snd . pE_internal

pAOp :: [Token] -> Err E.Abs.AOp
pAOp = fmap snd . pAOp_internal

pT :: [Token] -> Err E.Abs.T
pT = fmap snd . pT_internal

pT2 :: [Token] -> Err E.Abs.T
pT2 = fmap snd . pT2_internal

pListT :: [Token] -> Err [E.Abs.T]
pListT = fmap snd . pListT_internal

pT1 :: [Token] -> Err E.Abs.T
pT1 = fmap snd . pT1_internal
}

