-- This Happy file was machine-generated by the BNF converter
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
module E.Par where
import E.Abs
import E.Lex
import E.ErrM

}

%name pM M
%name pListD ListD
%name pD D
%name pConArgs ConArgs
%name pModuleName ModuleName
%name pGlobalRegion GlobalRegion
%name pDataRHS DataRHS
%name pUnboxedRHS UnboxedRHS
%name pListDataCon ListDataCon
%name pDataCon DataCon
%name pDCA DCA
%name pListRecordField ListRecordField
%name pRecordField RecordField
%name pS S
%name pListS ListS
%name pListCASE ListCASE
%name pCASE CASE
%name pListVarBind ListVarBind
%name pVarBind VarBind
%name pE13 E13
%name pListE ListE
%name pE12 E12
%name pE11 E11
%name pE10 E10
%name pE9 E9
%name pE8 E8
%name pE7 E7
%name pE6 E6
%name pE5 E5
%name pE4 E4
%name pE3 E3
%name pE2 E2
%name pE1 E1
%name pE E
%name pAOp AOp
%name pT T
%name pT2 T2
%name pListT ListT
%name pT1 T1
-- no lexer declaration
%monad { Err } { thenM } { returnM }
%tokentype {Token}
%token
  '!' { PT _ (TS _ 1) }
  '!=' { PT _ (TS _ 2) }
  '%' { PT _ (TS _ 3) }
  '%=' { PT _ (TS _ 4) }
  '&' { PT _ (TS _ 5) }
  '&&' { PT _ (TS _ 6) }
  '&=' { PT _ (TS _ 7) }
  '(' { PT _ (TS _ 8) }
  ')' { PT _ (TS _ 9) }
  '*' { PT _ (TS _ 10) }
  '*=' { PT _ (TS _ 11) }
  '+' { PT _ (TS _ 12) }
  '++' { PT _ (TS _ 13) }
  '+=' { PT _ (TS _ 14) }
  ',' { PT _ (TS _ 15) }
  '-' { PT _ (TS _ 16) }
  '--' { PT _ (TS _ 17) }
  '-=' { PT _ (TS _ 18) }
  '->' { PT _ (TS _ 19) }
  '.' { PT _ (TS _ 20) }
  '/' { PT _ (TS _ 21) }
  '/=' { PT _ (TS _ 22) }
  ':' { PT _ (TS _ 23) }
  '::' { PT _ (TS _ 24) }
  ':=' { PT _ (TS _ 25) }
  ';' { PT _ (TS _ 26) }
  '<' { PT _ (TS _ 27) }
  '<<' { PT _ (TS _ 28) }
  '<<=' { PT _ (TS _ 29) }
  '<=' { PT _ (TS _ 30) }
  '=' { PT _ (TS _ 31) }
  '==' { PT _ (TS _ 32) }
  '=>' { PT _ (TS _ 33) }
  '>' { PT _ (TS _ 34) }
  '>=' { PT _ (TS _ 35) }
  '>>' { PT _ (TS _ 36) }
  '>>=' { PT _ (TS _ 37) }
  '[' { PT _ (TS _ 38) }
  ']' { PT _ (TS _ 39) }
  '^' { PT _ (TS _ 40) }
  '^=' { PT _ (TS _ 41) }
  '_' { PT _ (TS _ 42) }
  'break' { PT _ (TS _ 43) }
  'case' { PT _ (TS _ 44) }
  'continue' { PT _ (TS _ 45) }
  'data' { PT _ (TS _ 46) }
  'default' { PT _ (TS _ 47) }
  'else' { PT _ (TS _ 48) }
  'end' { PT _ (TS _ 49) }
  'for' { PT _ (TS _ 50) }
  'if' { PT _ (TS _ 51) }
  'import' { PT _ (TS _ 52) }
  'memory' { PT _ (TS _ 53) }
  'of' { PT _ (TS _ 54) }
  'region' { PT _ (TS _ 55) }
  'return' { PT _ (TS _ 56) }
  'storage' { PT _ (TS _ 57) }
  'then' { PT _ (TS _ 58) }
  'tstorage' { PT _ (TS _ 59) }
  'type' { PT _ (TS _ 60) }
  'var' { PT _ (TS _ 61) }
  'while' { PT _ (TS _ 62) }
  '{' { PT _ (TS _ 63) }
  '|' { PT _ (TS _ 64) }
  '|=' { PT _ (TS _ 65) }
  '||' { PT _ (TS _ 66) }
  '}' { PT _ (TS _ 67) }
  '~' { PT _ (TS _ 68) }

L_ident  { PT _ (TV $$) }
L_integ  { PT _ (TI $$) }
L_quoted { PT _ (TL $$) }
L_UIdent { PT _ (T_UIdent $$) }
L_Infix { PT _ (T_Infix $$) }
L_HexInteger { PT _ (T_HexInteger $$) }


%%

Ident   :: { Ident }   : L_ident  { Ident $1 }
Integer :: { Integer } : L_integ  { (read ( $1)) :: Integer }
String  :: { String }  : L_quoted {  $1 }
UIdent    :: { UIdent} : L_UIdent { UIdent ($1)}
Infix    :: { Infix} : L_Infix { Infix ($1)}
HexInteger    :: { HexInteger} : L_HexInteger { HexInteger ($1)}

M :: { M }
M : ListD { E.Abs.Module $1 }
ListD :: { [D] }
ListD : {- empty -} { [] }
      | D { (:[]) $1 }
      | D ';' ListD { (:) $1 $3 }
D :: { D }
D : 'default' UIdent '=' T { E.Abs.Default $2 $4 }
  | Ident E13 ':=' S { E.Abs.Defun $1 $2 $4 }
  | Ident ':' T { E.Abs.TySig $1 $3 }
  | UIdent ':' T { E.Abs.KindSig $1 $3 }
  | 'type' ConArgs '=' T { E.Abs.TySyn $2 $4 }
  | 'import' ModuleName { E.Abs.Import $2 }
  | GlobalRegion VarBind { E.Abs.Global $1 $2 }
  | 'data' ConArgs '=' DataRHS { E.Abs.Data $2 $4 }
  | Ident ':=' E { E.Abs.StaticData $1 $3 }
ConArgs :: { ConArgs }
ConArgs : UIdent { E.Abs.CANil $1 }
        | ConArgs Ident { E.Abs.CACons $1 $2 }
ModuleName :: { ModuleName }
ModuleName : UIdent { E.Abs.MNil $1 }
           | UIdent '.' ModuleName { E.Abs.MCons $1 $3 }
GlobalRegion :: { GlobalRegion }
GlobalRegion : 'memory' { E.Abs.Memory }
             | 'storage' { E.Abs.Storage }
             | 'tstorage' { E.Abs.TStorage }
DataRHS :: { DataRHS }
DataRHS : UnboxedRHS 'region' Ident { E.Abs.Boxed $1 $3 }
        | UnboxedRHS { E.Abs.Unboxed $1 }
UnboxedRHS :: { UnboxedRHS }
UnboxedRHS : '{' ListDataCon '}' { E.Abs.URHS $2 }
ListDataCon :: { [DataCon] }
ListDataCon : {- empty -} { [] }
            | DataCon { (:[]) $1 }
            | DataCon ';' ListDataCon { (:) $1 $3 }
DataCon :: { DataCon }
DataCon : DCA { E.Abs.DCArgs $1 }
        | UIdent '{' ListRecordField '}' { E.Abs.DCRecord $1 $3 }
DCA :: { DCA }
DCA : UIdent { E.Abs.DCANil $1 } | DCA T1 { E.Abs.DCACons $1 $2 }
ListRecordField :: { [RecordField] }
ListRecordField : {- empty -} { [] }
                | RecordField { (:[]) $1 }
                | RecordField ',' ListRecordField { (:) $1 $3 }
RecordField :: { RecordField }
RecordField : Ident ':' T { E.Abs.RF $1 $3 }
S :: { S }
S : E { E.Abs.SE $1 }
  | 'if' E 'then' S 'else' S 'end' { E.Abs.If $2 $4 $6 }
  | 'while' '(' E ')' S { E.Abs.While $3 $5 }
  | 'return' E { E.Abs.Return $2 }
  | '{' ListS '}' { E.Abs.Do $2 }
  | 'case' E 'of' '{' ListCASE '}' { E.Abs.Case $2 $5 }
  | 'break' { E.Abs.Break }
  | 'continue' { E.Abs.Continue }
  | 'for' '(' S ';' E ';' S ')' S { E.Abs.For $3 $5 $7 $9 }
  | 'var' ListVarBind { E.Abs.Declare $2 }
ListS :: { [S] }
ListS : {- empty -} { [] }
      | S { (:[]) $1 }
      | S ';' ListS { (:) $1 $3 }
ListCASE :: { [CASE] }
ListCASE : {- empty -} { [] }
         | CASE { (:[]) $1 }
         | CASE ';' ListCASE { (:) $1 $3 }
CASE :: { CASE }
CASE : E '=>' S { E.Abs.C $1 $3 }
ListVarBind :: { [VarBind] }
ListVarBind : VarBind { (:[]) $1 }
            | VarBind ',' ListVarBind { (:) $1 $3 }
VarBind :: { VarBind }
VarBind : Ident { E.Abs.JustVar $1 }
        | Ident '=' E { E.Abs.VarIs $1 $3 }
E13 :: { E }
E13 : '(' ')' { E.Abs.EmptyTuple }
    | '(' E ',' ListE ')' { E.Abs.Tuple $2 $4 }
    | HexInteger { E.Abs.HexInt $1 }
    | Integer { E.Abs.Int $1 }
    | Ident { E.Abs.Var $1 }
    | String { E.Abs.String $1 }
    | UIdent { E.Abs.Con $1 }
    | '_' { E.Abs.Wild }
    | '(' E ')' { $2 }
ListE :: { [E] }
ListE : E { (:[]) $1 } | E ',' ListE { (:) $1 $3 }
E12 :: { E }
E12 : E12 '++' { E.Abs.PlusPlusPost $1 }
    | E12 '--' { E.Abs.MinusMinusPost $1 }
    | E12 '[' E ']' { E.Abs.Index $1 $3 }
    | E12 '.' Ident { E.Abs.Dot $1 $3 }
    | E12 '->' Ident { E.Abs.Arrow $1 $3 }
    | E12 E13 { E.Abs.App $1 $2 }
    | E13 { $1 }
E11 :: { E }
E11 : '++' E11 { E.Abs.PlusPlusPre $2 }
    | '--' E11 { E.Abs.MinusMinusPre $2 }
    | '-' E11 { E.Abs.Negate $2 }
    | '!' E11 { E.Abs.Not $2 }
    | '~' E11 { E.Abs.BitwiseNot $2 }
    | '*' E11 { E.Abs.Deref $2 }
    | '&' E11 { E.Abs.AddressOf $2 }
    | E12 { $1 }
E10 :: { E }
E10 : E10 '*' E11 { E.Abs.Mul $1 $3 }
    | E10 '/' E11 { E.Abs.Div $1 $3 }
    | E10 '%' E11 { E.Abs.Mod $1 $3 }
    | E11 { $1 }
E9 :: { E }
E9 : E9 '+' E10 { E.Abs.Plus $1 $3 }
   | E9 '-' E10 { E.Abs.Minus $1 $3 }
   | E10 { $1 }
E8 :: { E }
E8 : E8 '<<' E9 { E.Abs.Shl $1 $3 }
   | E8 '>>' E9 { E.Abs.Shr $1 $3 }
   | E9 { $1 }
E7 :: { E }
E7 : E7 '<' E8 { E.Abs.MyLT $1 $3 }
   | E7 '<=' E8 { E.Abs.LTE $1 $3 }
   | E7 '>' E8 { E.Abs.MyGT $1 $3 }
   | E7 '>=' E8 { E.Abs.GTE $1 $3 }
   | E8 { $1 }
E6 :: { E }
E6 : E6 '==' E7 { E.Abs.Eq $1 $3 }
   | E6 '!=' E7 { E.Abs.NEq $1 $3 }
   | E7 { $1 }
E5 :: { E }
E5 : E5 '&' E6 { E.Abs.BitwiseAnd $1 $3 } | E6 { $1 }
E4 :: { E }
E4 : E4 '^' E5 { E.Abs.BitwiseXor $1 $3 } | E5 { $1 }
E3 :: { E }
E3 : E3 '|' E4 { E.Abs.BitwiseOr $1 $3 } | E4 { $1 }
E2 :: { E }
E2 : E2 '&&' E3 { E.Abs.And $1 $3 } | E3 { $1 }
E1 :: { E }
E1 : E1 '||' E2 { E.Abs.Or $1 $3 } | E2 { $1 }
E :: { E }
E : E1 { $1 }
  | E1 AOp E { E.Abs.Assign $1 $2 $3 }
  | E1 '::' T { E.Abs.TypeAnnot $1 $3 }
AOp :: { AOp }
AOp : '=' { E.Abs.EqEq }
    | '+=' { E.Abs.PlusEq }
    | '-=' { E.Abs.MinusEq }
    | '*=' { E.Abs.MulEq }
    | '/=' { E.Abs.DivEq }
    | '%=' { E.Abs.ModEq }
    | '<<=' { E.Abs.ShlEq }
    | '>>=' { E.Abs.ShrEq }
    | '&=' { E.Abs.AndEq }
    | '^=' { E.Abs.XorEq }
    | '|=' { E.Abs.OrEq }
T :: { T }
T : T1 '->' T { E.Abs.TArrow $1 $3 }
  | T1 '[' T ']' { E.Abs.TArray $1 $3 }
  | T1 { $1 }
T2 :: { T }
T2 : Ident { E.Abs.TVar $1 }
   | Integer { E.Abs.TNat $1 }
   | UIdent { E.Abs.TCon $1 }
   | '(' ')' { E.Abs.TEmptyTup }
   | '(' T ',' ListT ')' { E.Abs.TTup $2 $4 }
   | '(' T ')' { $2 }
ListT :: { [T] }
ListT : T { (:[]) $1 } | T ',' ListT { (:) $1 $3 }
T1 :: { T }
T1 : T1 T2 { E.Abs.TApp $1 $2 } | T2 { $1 }
{

returnM :: a -> Err a
returnM = return

thenM :: Err a -> (a -> Err b) -> Err b
thenM = (>>=)

happyError :: [Token] -> Err a
happyError ts =
  Bad $ "syntax error at " ++ tokenPos ts ++ 
  case ts of
    [] -> []
    [Err _] -> " due to lexer error"
    _ -> " before " ++ unwords (map (id . prToken) (take 4 ts))

myLexer = tokens
}

