-- This Happy file was machine-generated by the BNF converter
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
module E.Par where
import E.Abs
import E.Lex
import E.ErrM

}

%name pM M
%name pListD ListD
%name pD D
%name pConArgs ConArgs
%name pS S
%name pListS ListS
%name pE E
%name pE1 E1
%name pE2 E2
%name pE3 E3
%name pListE ListE
%name pListField ListField
%name pOS OS
%name pField Field
-- no lexer declaration
%monad { Err } { thenM } { returnM }
%tokentype {Token}
%token
  '(' { PT _ (TS _ 1) }
  ')' { PT _ (TS _ 2) }
  ',' { PT _ (TS _ 3) }
  '.' { PT _ (TS _ 4) }
  ':' { PT _ (TS _ 5) }
  ':=' { PT _ (TS _ 6) }
  ';' { PT _ (TS _ 7) }
  '=' { PT _ (TS _ 8) }
  '_' { PT _ (TS _ 9) }
  'do' { PT _ (TS _ 10) }
  'else' { PT _ (TS _ 11) }
  'end' { PT _ (TS _ 12) }
  'if' { PT _ (TS _ 13) }
  'module' { PT _ (TS _ 14) }
  'return' { PT _ (TS _ 15) }
  'then' { PT _ (TS _ 16) }
  'type' { PT _ (TS _ 17) }
  'while' { PT _ (TS _ 18) }
  '{' { PT _ (TS _ 19) }
  '}' { PT _ (TS _ 20) }

L_ident  { PT _ (TV $$) }
L_integ  { PT _ (TI $$) }
L_UIdent { PT _ (T_UIdent $$) }
L_Infix { PT _ (T_Infix $$) }


%%

Ident   :: { Ident }   : L_ident  { Ident $1 }
Integer :: { Integer } : L_integ  { (read ( $1)) :: Integer }
UIdent    :: { UIdent} : L_UIdent { UIdent ($1)}
Infix    :: { Infix} : L_Infix { Infix ($1)}

M :: { M }
M : 'module' '{' ListD '}' { E.Abs.Module $3 }
ListD :: { [D] }
ListD : {- empty -} { [] }
      | D { (:[]) $1 }
      | D ';' ListD { (:) $1 $3 }
D :: { D }
D : Ident E3 ':=' S { E.Abs.Defun $1 $2 $4 }
  | Ident ':' E { E.Abs.TySig $1 $3 }
  | 'type' ConArgs '=' E { E.Abs.TySyn $2 $4 }
ConArgs :: { ConArgs }
ConArgs : UIdent { E.Abs.CANil $1 }
        | ConArgs Ident { E.Abs.CACons $1 $2 }
S :: { S }
S : E { E.Abs.SE $1 }
  | 'if' E 'then' S 'else' S 'end' { E.Abs.If $2 $4 $6 }
  | 'while' '(' E ')' S { E.Abs.While $3 $5 }
  | 'return' E { E.Abs.Return $2 }
  | 'do' '{' ListS '}' { E.Abs.Do $3 }
ListS :: { [S] }
ListS : {- empty -} { [] }
      | S { (:[]) $1 }
      | S ';' ListS { (:) $1 $3 }
E :: { E }
E : E3 '=' E1 { E.Abs.Assign $1 $3 } | E1 { $1 }
E1 :: { E }
E1 : E2 Infix OS { E.Abs.Ops $1 $2 $3 }
   | Infix E1 { E.Abs.PrefixOp $1 $2 }
   | E2 { $1 }
E2 :: { E }
E2 : E2 E3 { E.Abs.App $1 $2 } | E3 { $1 }
E3 :: { E }
E3 : Ident { E.Abs.Var $1 }
   | UIdent { E.Abs.Con $1 }
   | E3 '.' Ident { E.Abs.Dot $1 $3 }
   | Integer { E.Abs.Int $1 }
   | '(' ')' { E.Abs.EmptyTup }
   | '(' E ',' ListE ')' { E.Abs.Tup $2 $4 }
   | '{' '}' { E.Abs.EmptyStruct }
   | '{' ListField '}' { E.Abs.EStruct $2 }
   | '_' { E.Abs.Wild }
   | '(' E ')' { $2 }
ListE :: { [E] }
ListE : {- empty -} { [] }
      | E { (:[]) $1 }
      | E ',' ListE { (:) $1 $3 }
ListField :: { [Field] }
ListField : Field { (:[]) $1 } | Field ',' ListField { (:) $1 $3 }
OS :: { OS }
OS : E2 { E.Abs.OSNil $1 } | E2 Infix OS { E.Abs.OSCons $1 $2 $3 }
Field :: { Field }
Field : Ident ':' E { E.Abs.Named $1 $3 } | E { E.Abs.Anon $1 }
{

returnM :: a -> Err a
returnM = return

thenM :: Err a -> (a -> Err b) -> Err b
thenM = (>>=)

happyError :: [Token] -> Err a
happyError ts =
  Bad $ "syntax error at " ++ tokenPos ts ++ 
  case ts of
    [] -> []
    [Err _] -> " due to lexer error"
    _ -> " before " ++ unwords (map (id . prToken) (take 4 ts))

myLexer = tokens
}

