{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module E.Print where

-- pretty-printer generated by the BNF converter

import E.Abs
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))


instance Print UIdent where
  prt _ (UIdent i) = doc (showString ( i))


instance Print Infix where
  prt _ (Infix i) = doc (showString ( i))



instance Print M where
  prt i e = case e of
    Module ds -> prPrec i 0 (concatD [doc (showString "module"), doc (showString "{"), prt 0 ds, doc (showString "}")])

instance Print D where
  prt i e = case e of
    Defun id e_ s -> prPrec i 0 (concatD [prt 0 id, prt 3 e_, doc (showString ":="), prt 0 s])
    TySig id e_ -> prPrec i 0 (concatD [prt 0 id, doc (showString ":"), prt 0 e_])
    TySyn conargs e_ -> prPrec i 0 (concatD [doc (showString "type"), prt 0 conargs, doc (showString "="), prt 0 e_])
    Import modulename -> prPrec i 0 (concatD [doc (showString "import"), prt 0 modulename])
    Global globalregion id e_ -> prPrec i 0 (concatD [prt 0 globalregion, prt 0 id, doc (showString ":"), prt 0 e_])
    Data conlhs datacons -> prPrec i 0 (concatD [doc (showString "data"), prt 0 conlhs, doc (showString "="), doc (showString "{"), prt 0 datacons, doc (showString "}")])
    Enum uident enumcons -> prPrec i 0 (concatD [doc (showString "enum"), prt 0 uident, doc (showString "{"), prt 0 enumcons, doc (showString "}")])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ";"), prt 0 xs])
instance Print ConArgs where
  prt i e = case e of
    CANil uident -> prPrec i 0 (concatD [prt 0 uident])
    CACons conargs id -> prPrec i 0 (concatD [prt 0 conargs, prt 0 id])

instance Print ModuleName where
  prt i e = case e of
    MNil uident -> prPrec i 0 (concatD [prt 0 uident])
    MCons uident modulename -> prPrec i 0 (concatD [prt 0 uident, doc (showString "."), prt 0 modulename])

instance Print GlobalRegion where
  prt i e = case e of
    Memory -> prPrec i 0 (concatD [doc (showString "memory")])
    Storage -> prPrec i 0 (concatD [doc (showString "storage")])
    TStorage -> prPrec i 0 (concatD [doc (showString "tstorage")])

instance Print ConLHS where
  prt i e = case e of
    CLNil uident id -> prPrec i 0 (concatD [prt 0 uident, prt 0 id])
    CLCons conlhs id -> prPrec i 0 (concatD [prt 0 conlhs, prt 0 id])

instance Print DataCon where
  prt i e = case e of
    DC uident e_ -> prPrec i 0 (concatD [prt 0 uident, prt 3 e_])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ";"), prt 0 xs])
instance Print EnumCon where
  prt i e = case e of
    EC id -> prPrec i 0 (concatD [prt 0 id])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print S where
  prt i e = case e of
    SE e_ -> prPrec i 0 (concatD [prt 0 e_])
    If e_ s1 s2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 e_, doc (showString "then"), prt 0 s1, doc (showString "else"), prt 0 s2, doc (showString "end")])
    While e_ s -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 e_, doc (showString ")"), prt 0 s])
    Return e_ -> prPrec i 0 (concatD [doc (showString "return"), prt 0 e_])
    Do ss -> prPrec i 0 (concatD [doc (showString "do"), doc (showString "{"), prt 0 ss, doc (showString "}")])
    Case e_ cases -> prPrec i 0 (concatD [doc (showString "case"), prt 0 e_, doc (showString "of"), doc (showString "{"), prt 0 cases, doc (showString "}")])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ";"), prt 0 xs])
instance Print CASE where
  prt i e = case e of
    C e_ s -> prPrec i 0 (concatD [prt 2 e_, doc (showString "=>"), prt 0 s])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ";"), prt 0 xs])
instance Print E where
  prt i e = case e of
    Index e_1 e_2 -> prPrec i 0 (concatD [prt 3 e_1, doc (showString "["), prt 0 e_2, doc (showString "]")])
    Assign e_1 e_2 -> prPrec i 0 (concatD [prt 3 e_1, doc (showString "="), prt 1 e_2])
    Ops e_ infix_ os -> prPrec i 1 (concatD [prt 2 e_, prt 0 infix_, prt 0 os])
    PrefixOp infix_ e_ -> prPrec i 1 (concatD [prt 0 infix_, prt 1 e_])
    App e_1 e_2 -> prPrec i 2 (concatD [prt 2 e_1, prt 3 e_2])
    Var id -> prPrec i 3 (concatD [prt 0 id])
    Con uident -> prPrec i 3 (concatD [prt 0 uident])
    Dot e_ id -> prPrec i 3 (concatD [prt 3 e_, doc (showString "."), prt 0 id])
    Hash e_ n -> prPrec i 3 (concatD [prt 3 e_, doc (showString "#"), prt 0 n])
    Int n -> prPrec i 3 (concatD [prt 0 n])
    Str str -> prPrec i 3 (concatD [prt 0 str])
    EmptyTup -> prPrec i 3 (concatD [doc (showString "("), doc (showString ")")])
    Tup e_ es -> prPrec i 3 (concatD [doc (showString "("), prt 0 e_, doc (showString ","), prt 0 es, doc (showString ")")])
    EmptyStruct -> prPrec i 3 (concatD [doc (showString "{"), doc (showString "}")])
    EStruct fields -> prPrec i 3 (concatD [doc (showString "{"), prt 0 fields, doc (showString "}")])
    Wild -> prPrec i 3 (concatD [doc (showString "_")])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print OS where
  prt i e = case e of
    OSNil e_ -> prPrec i 0 (concatD [prt 2 e_])
    OSCons e_ infix_ os -> prPrec i 0 (concatD [prt 2 e_, prt 0 infix_, prt 0 os])

instance Print Field where
  prt i e = case e of
    AnnotPad padinfo field -> prPrec i 0 (concatD [doc (showString "pad"), prt 0 padinfo, prt 0 field])
    AnnotAlign padinfo field -> prPrec i 0 (concatD [doc (showString "align"), prt 0 padinfo, prt 0 field])
    Named id e_ -> prPrec i 0 (concatD [prt 0 id, doc (showString ":"), prt 0 e_])
    Anon e_ -> prPrec i 0 (concatD [prt 0 e_])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print PadInfo where
  prt i e = case e of
    Bit -> prPrec i 0 (concatD [doc (showString "bit")])
    Byte -> prPrec i 0 (concatD [doc (showString "byte")])
    Word -> prPrec i 0 (concatD [doc (showString "word")])


