-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for E.

module E.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified E.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print E.Abs.Ident where
  prt _ (E.Abs.Ident i) = doc $ showString i
instance Print E.Abs.UIdent where
  prt _ (E.Abs.UIdent i) = doc $ showString i
instance Print E.Abs.Infix where
  prt _ (E.Abs.Infix i) = doc $ showString i
instance Print E.Abs.HexInteger where
  prt _ (E.Abs.HexInteger i) = doc $ showString i
instance Print E.Abs.M where
  prt i = \case
    E.Abs.Module ds -> prPrec i 0 (concatD [prt 0 ds])

instance Print [E.Abs.D] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print E.Abs.D where
  prt i = \case
    E.Abs.Default uident t -> prPrec i 0 (concatD [doc (showString "default"), prt 0 uident, doc (showString "="), prt 0 t])
    E.Abs.Defun id_ e_ s -> prPrec i 0 (concatD [prt 0 id_, prt 13 e_, doc (showString ":="), prt 0 s])
    E.Abs.Instance id_ t e_ s -> prPrec i 0 (concatD [doc (showString "instance"), prt 0 id_, doc (showString ":"), prt 0 t, doc (showString "where"), prt 13 e_, doc (showString ":="), prt 0 s])
    E.Abs.TySig id_ t -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 t])
    E.Abs.KindSig uident t -> prPrec i 0 (concatD [prt 0 uident, doc (showString ":"), prt 0 t])
    E.Abs.TySyn conargs t -> prPrec i 0 (concatD [doc (showString "type"), prt 0 conargs, doc (showString "="), prt 0 t])
    E.Abs.Import modulename -> prPrec i 0 (concatD [doc (showString "import"), prt 0 modulename])
    E.Abs.Global globalregion varbind -> prPrec i 0 (concatD [prt 0 globalregion, prt 0 varbind])
    E.Abs.Data conargs datarhs -> prPrec i 0 (concatD [doc (showString "data"), prt 0 conargs, doc (showString "="), prt 0 datarhs])
    E.Abs.Tag conargs t contags -> prPrec i 0 (concatD [doc (showString "tag"), prt 0 conargs, doc (showString "="), prt 0 t, doc (showString "where"), doc (showString "{"), prt 0 contags, doc (showString "}")])

instance Print E.Abs.ConArgs where
  prt i = \case
    E.Abs.CANil uident -> prPrec i 0 (concatD [prt 0 uident])
    E.Abs.CACons conargs id_ -> prPrec i 0 (concatD [prt 0 conargs, prt 0 id_])

instance Print E.Abs.ModuleName where
  prt i = \case
    E.Abs.MNil uident -> prPrec i 0 (concatD [prt 0 uident])
    E.Abs.MCons uident modulename -> prPrec i 0 (concatD [prt 0 uident, doc (showString "."), prt 0 modulename])

instance Print E.Abs.GlobalRegion where
  prt i = \case
    E.Abs.Memory -> prPrec i 0 (concatD [doc (showString "memory")])
    E.Abs.Storage -> prPrec i 0 (concatD [doc (showString "storage")])
    E.Abs.TStorage -> prPrec i 0 (concatD [doc (showString "tstorage")])
    E.Abs.Code -> prPrec i 0 (concatD [doc (showString "code")])

instance Print E.Abs.DataRHS where
  prt i = \case
    E.Abs.Boxed unboxedrhs id_ -> prPrec i 0 (concatD [prt 0 unboxedrhs, doc (showString "region"), prt 0 id_])
    E.Abs.Unboxed unboxedrhs -> prPrec i 0 (concatD [prt 0 unboxedrhs])

instance Print E.Abs.UnboxedRHS where
  prt i = \case
    E.Abs.URHS datacons -> prPrec i 0 (concatD [doc (showString "{"), prt 0 datacons, doc (showString "}")])

instance Print [E.Abs.DataCon] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print E.Abs.DataCon where
  prt i = \case
    E.Abs.DCArgs dca -> prPrec i 0 (concatD [prt 0 dca])
    E.Abs.DCRecord uident recordfields -> prPrec i 0 (concatD [prt 0 uident, doc (showString "{"), prt 0 recordfields, doc (showString "}")])

instance Print E.Abs.DCA where
  prt i = \case
    E.Abs.DCANil uident -> prPrec i 0 (concatD [prt 0 uident])
    E.Abs.DCACons dca t -> prPrec i 0 (concatD [prt 0 dca, prt 2 t])

instance Print [E.Abs.RecordField] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print E.Abs.RecordField where
  prt i = \case
    E.Abs.RF id_ t -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 t])

instance Print [E.Abs.ConTag] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print E.Abs.ConTag where
  prt i = \case
    E.Abs.ConTag uident e_ -> prPrec i 0 (concatD [prt 0 uident, doc (showString ":"), prt 0 e_])

instance Print E.Abs.S where
  prt i = \case
    E.Abs.SE e_ -> prPrec i 0 (concatD [prt 0 e_])
    E.Abs.If e_ s1 s2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 e_, doc (showString "then"), prt 0 s1, doc (showString "else"), prt 0 s2, doc (showString "end")])
    E.Abs.While e_ s -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 e_, doc (showString ")"), prt 0 s])
    E.Abs.Return e_ -> prPrec i 0 (concatD [doc (showString "return"), prt 0 e_])
    E.Abs.Do ss -> prPrec i 0 (concatD [doc (showString "{"), prt 0 ss, doc (showString "}")])
    E.Abs.Case e_ cases -> prPrec i 0 (concatD [doc (showString "case"), prt 0 e_, doc (showString "of"), doc (showString "{"), prt 0 cases, doc (showString "}")])
    E.Abs.Break -> prPrec i 0 (concatD [doc (showString "break")])
    E.Abs.Continue -> prPrec i 0 (concatD [doc (showString "continue")])
    E.Abs.For s1 e_ s2 s3 -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 s1, doc (showString ";"), prt 0 e_, doc (showString ";"), prt 0 s2, doc (showString ")"), prt 0 s3])
    E.Abs.Declare varbinds -> prPrec i 0 (concatD [doc (showString "var"), prt 0 varbinds])

instance Print [E.Abs.S] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [E.Abs.CASE] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print E.Abs.CASE where
  prt i = \case
    E.Abs.C e_ s -> prPrec i 0 (concatD [prt 0 e_, doc (showString "=>"), prt 0 s])

instance Print [E.Abs.VarBind] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print E.Abs.VarBind where
  prt i = \case
    E.Abs.JustVar id_ -> prPrec i 0 (concatD [prt 0 id_])
    E.Abs.VarIs id_ e_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 e_])

instance Print E.Abs.E where
  prt i = \case
    E.Abs.EmptyTuple -> prPrec i 13 (concatD [doc (showString "("), doc (showString ")")])
    E.Abs.Tuple e_ es -> prPrec i 13 (concatD [doc (showString "("), prt 0 e_, doc (showString ","), prt 0 es, doc (showString ")")])
    E.Abs.HexInt hexinteger -> prPrec i 13 (concatD [prt 0 hexinteger])
    E.Abs.Int n -> prPrec i 13 (concatD [prt 0 n])
    E.Abs.Var id_ -> prPrec i 13 (concatD [prt 0 id_])
    E.Abs.String str -> prPrec i 13 (concatD [printString str])
    E.Abs.ConRecord uident efields -> prPrec i 13 (concatD [prt 0 uident, doc (showString "{"), prt 0 efields, doc (showString "}")])
    E.Abs.Con uident -> prPrec i 13 (concatD [prt 0 uident])
    E.Abs.Wild -> prPrec i 13 (concatD [doc (showString "_")])
    E.Abs.PlusPlusPost e_ -> prPrec i 12 (concatD [prt 12 e_, doc (showString "++")])
    E.Abs.MinusMinusPost e_ -> prPrec i 12 (concatD [prt 12 e_, doc (showString "--")])
    E.Abs.Index e_1 e_2 -> prPrec i 12 (concatD [prt 12 e_1, doc (showString "["), prt 0 e_2, doc (showString "]")])
    E.Abs.Dot e_ id_ -> prPrec i 12 (concatD [prt 12 e_, doc (showString "."), prt 0 id_])
    E.Abs.Bang e_1 e_2 -> prPrec i 12 (concatD [prt 12 e_1, doc (showString "!"), prt 13 e_2])
    E.Abs.Arrow e_ id_ -> prPrec i 12 (concatD [prt 12 e_, doc (showString "->"), prt 0 id_])
    E.Abs.App e_1 e_2 -> prPrec i 12 (concatD [prt 12 e_1, prt 13 e_2])
    E.Abs.PlusPlusPre e_ -> prPrec i 11 (concatD [doc (showString "++"), prt 11 e_])
    E.Abs.MinusMinusPre e_ -> prPrec i 11 (concatD [doc (showString "--"), prt 11 e_])
    E.Abs.Negate e_ -> prPrec i 11 (concatD [doc (showString "-"), prt 11 e_])
    E.Abs.Not e_ -> prPrec i 11 (concatD [doc (showString "!"), prt 11 e_])
    E.Abs.BitwiseNot e_ -> prPrec i 11 (concatD [doc (showString "~"), prt 11 e_])
    E.Abs.Deref e_ -> prPrec i 11 (concatD [doc (showString "*"), prt 11 e_])
    E.Abs.AddressOf e_ -> prPrec i 11 (concatD [doc (showString "&"), prt 11 e_])
    E.Abs.Mul e_1 e_2 -> prPrec i 10 (concatD [prt 10 e_1, doc (showString "*"), prt 11 e_2])
    E.Abs.Div e_1 e_2 -> prPrec i 10 (concatD [prt 10 e_1, doc (showString "/"), prt 11 e_2])
    E.Abs.Mod e_1 e_2 -> prPrec i 10 (concatD [prt 10 e_1, doc (showString "%"), prt 11 e_2])
    E.Abs.Plus e_1 e_2 -> prPrec i 9 (concatD [prt 9 e_1, doc (showString "+"), prt 10 e_2])
    E.Abs.Minus e_1 e_2 -> prPrec i 9 (concatD [prt 9 e_1, doc (showString "-"), prt 10 e_2])
    E.Abs.Shl e_1 e_2 -> prPrec i 8 (concatD [prt 8 e_1, doc (showString "<<"), prt 9 e_2])
    E.Abs.Shr e_1 e_2 -> prPrec i 8 (concatD [prt 8 e_1, doc (showString ">>"), prt 9 e_2])
    E.Abs.MyLT e_1 e_2 -> prPrec i 7 (concatD [prt 7 e_1, doc (showString "<"), prt 8 e_2])
    E.Abs.LTE e_1 e_2 -> prPrec i 7 (concatD [prt 7 e_1, doc (showString "<="), prt 8 e_2])
    E.Abs.MyGT e_1 e_2 -> prPrec i 7 (concatD [prt 7 e_1, doc (showString ">"), prt 8 e_2])
    E.Abs.GTE e_1 e_2 -> prPrec i 7 (concatD [prt 7 e_1, doc (showString ">="), prt 8 e_2])
    E.Abs.Eq e_1 e_2 -> prPrec i 6 (concatD [prt 6 e_1, doc (showString "=="), prt 7 e_2])
    E.Abs.NEq e_1 e_2 -> prPrec i 6 (concatD [prt 6 e_1, doc (showString "!="), prt 7 e_2])
    E.Abs.BitwiseAnd e_1 e_2 -> prPrec i 5 (concatD [prt 5 e_1, doc (showString "&"), prt 6 e_2])
    E.Abs.BitwiseXor e_1 e_2 -> prPrec i 4 (concatD [prt 4 e_1, doc (showString "^"), prt 5 e_2])
    E.Abs.BitwiseOr e_1 e_2 -> prPrec i 3 (concatD [prt 3 e_1, doc (showString "|"), prt 4 e_2])
    E.Abs.And e_1 e_2 -> prPrec i 2 (concatD [prt 2 e_1, doc (showString "&&"), prt 3 e_2])
    E.Abs.Or e_1 e_2 -> prPrec i 1 (concatD [prt 1 e_1, doc (showString "||"), prt 2 e_2])
    E.Abs.Assign e_1 aop e_2 -> prPrec i 0 (concatD [prt 1 e_1, prt 0 aop, prt 0 e_2])
    E.Abs.TypeAnnot e_ t -> prPrec i 0 (concatD [prt 1 e_, doc (showString "::"), prt 0 t])

instance Print [E.Abs.E] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [E.Abs.EField] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print E.Abs.EField where
  prt i = \case
    E.Abs.EField id_ e_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 e_])

instance Print E.Abs.AOp where
  prt i = \case
    E.Abs.EqEq -> prPrec i 0 (concatD [doc (showString "=")])
    E.Abs.PlusEq -> prPrec i 0 (concatD [doc (showString "+=")])
    E.Abs.MinusEq -> prPrec i 0 (concatD [doc (showString "-=")])
    E.Abs.MulEq -> prPrec i 0 (concatD [doc (showString "*=")])
    E.Abs.DivEq -> prPrec i 0 (concatD [doc (showString "/=")])
    E.Abs.ModEq -> prPrec i 0 (concatD [doc (showString "%=")])
    E.Abs.ShlEq -> prPrec i 0 (concatD [doc (showString "<<=")])
    E.Abs.ShrEq -> prPrec i 0 (concatD [doc (showString ">>=")])
    E.Abs.AndEq -> prPrec i 0 (concatD [doc (showString "&=")])
    E.Abs.XorEq -> prPrec i 0 (concatD [doc (showString "^=")])
    E.Abs.OrEq -> prPrec i 0 (concatD [doc (showString "|=")])

instance Print E.Abs.T where
  prt i = \case
    E.Abs.TArrow t1 t2 -> prPrec i 0 (concatD [prt 1 t1, doc (showString "->"), prt 0 t2])
    E.Abs.TVar id_ -> prPrec i 2 (concatD [prt 0 id_])
    E.Abs.TNat n -> prPrec i 2 (concatD [prt 0 n])
    E.Abs.TCon uident -> prPrec i 2 (concatD [prt 0 uident])
    E.Abs.TEmptyTup -> prPrec i 2 (concatD [doc (showString "("), doc (showString ")")])
    E.Abs.TTup t ts -> prPrec i 2 (concatD [doc (showString "("), prt 0 t, doc (showString ","), prt 0 ts, doc (showString ")")])
    E.Abs.TApp t1 t2 -> prPrec i 1 (concatD [prt 1 t1, prt 2 t2])
    E.Abs.TArray t1 t2 -> prPrec i 0 (concatD [prt 1 t1, doc (showString "["), prt 0 t2, doc (showString "]")])

instance Print [E.Abs.T] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]
