-- File generated by the BNF Converter (bnfc 2.9.6.3).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}

-- | Pretty-printer for E.

module E.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified E.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print E.Abs.Ident where
  prt _ (E.Abs.Ident i) = doc $ showString i
instance Print E.Abs.UIdent where
  prt _ (E.Abs.UIdent i) = doc $ showString i
instance Print E.Abs.Infix where
  prt _ (E.Abs.Infix i) = doc $ showString i
instance Print E.Abs.HexInteger where
  prt _ (E.Abs.HexInteger i) = doc $ showString i
instance Print (E.Abs.M' a) where
  prt i = \case
    E.Abs.Module _ ds -> prPrec i 0 (concatD [prt 0 ds])

instance Print [E.Abs.D' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print (E.Abs.D' a) where
  prt i = \case
    E.Abs.Default _ uident t -> prPrec i 0 (concatD [doc (showString "default"), prt 0 uident, doc (showString "="), prt 0 t])
    E.Abs.Defun _ id_ e_ s -> prPrec i 0 (concatD [prt 0 id_, prt 13 e_, doc (showString ":="), prt 0 s])
    E.Abs.Instance _ id_ t e_ s -> prPrec i 0 (concatD [doc (showString "instance"), prt 0 id_, doc (showString ":"), prt 0 t, doc (showString "where"), prt 13 e_, doc (showString ":="), prt 0 s])
    E.Abs.TySig _ id_ t -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 t])
    E.Abs.KindSig _ uident t -> prPrec i 0 (concatD [prt 0 uident, doc (showString ":"), prt 0 t])
    E.Abs.TySyn _ conargs t -> prPrec i 0 (concatD [doc (showString "type"), prt 0 conargs, doc (showString "="), prt 0 t])
    E.Abs.Import _ modulename -> prPrec i 0 (concatD [doc (showString "import"), prt 0 modulename])
    E.Abs.Global _ globalregion varbind -> prPrec i 0 (concatD [prt 0 globalregion, prt 0 varbind])
    E.Abs.Data _ conargs datarhs -> prPrec i 0 (concatD [doc (showString "data"), prt 0 conargs, doc (showString "="), prt 0 datarhs])
    E.Abs.Tag _ conargs t contags -> prPrec i 0 (concatD [doc (showString "tag"), prt 0 conargs, doc (showString "="), prt 0 t, doc (showString "where"), doc (showString "{"), prt 0 contags, doc (showString "}")])
    E.Abs.Contract _ id_ ds -> prPrec i 0 (concatD [doc (showString "contract"), prt 0 id_, doc (showString "{"), prt 0 ds, doc (showString "}")])

instance Print (E.Abs.ConArgs' a) where
  prt i = \case
    E.Abs.CANil _ uident -> prPrec i 0 (concatD [prt 0 uident])
    E.Abs.CACons _ conargs id_ -> prPrec i 0 (concatD [prt 0 conargs, prt 0 id_])

instance Print (E.Abs.ModuleName' a) where
  prt i = \case
    E.Abs.MNil _ uident -> prPrec i 0 (concatD [prt 0 uident])
    E.Abs.MCons _ uident modulename -> prPrec i 0 (concatD [prt 0 uident, doc (showString "."), prt 0 modulename])

instance Print (E.Abs.GlobalRegion' a) where
  prt i = \case
    E.Abs.Memory _ -> prPrec i 0 (concatD [doc (showString "memory")])
    E.Abs.Storage _ -> prPrec i 0 (concatD [doc (showString "storage")])
    E.Abs.TStorage _ -> prPrec i 0 (concatD [doc (showString "tstorage")])
    E.Abs.Code _ -> prPrec i 0 (concatD [doc (showString "code")])

instance Print (E.Abs.DataRHS' a) where
  prt i = \case
    E.Abs.Boxed _ unboxedrhs id_ -> prPrec i 0 (concatD [prt 0 unboxedrhs, doc (showString "region"), prt 0 id_])
    E.Abs.Unboxed _ unboxedrhs -> prPrec i 0 (concatD [prt 0 unboxedrhs])

instance Print (E.Abs.UnboxedRHS' a) where
  prt i = \case
    E.Abs.URHS _ datacons -> prPrec i 0 (concatD [doc (showString "{"), prt 0 datacons, doc (showString "}")])

instance Print [E.Abs.DataCon' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print (E.Abs.DataCon' a) where
  prt i = \case
    E.Abs.DCArgs _ dca -> prPrec i 0 (concatD [prt 0 dca])
    E.Abs.DCRecord _ uident recordfields -> prPrec i 0 (concatD [prt 0 uident, doc (showString "{"), prt 0 recordfields, doc (showString "}")])

instance Print (E.Abs.DCA' a) where
  prt i = \case
    E.Abs.DCANil _ uident -> prPrec i 0 (concatD [prt 0 uident])
    E.Abs.DCACons _ dca t -> prPrec i 0 (concatD [prt 0 dca, prt 2 t])

instance Print [E.Abs.RecordField' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (E.Abs.RecordField' a) where
  prt i = \case
    E.Abs.RF _ id_ t -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 t])

instance Print [E.Abs.ConTag' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (E.Abs.ConTag' a) where
  prt i = \case
    E.Abs.ConTag _ uident e_ -> prPrec i 0 (concatD [prt 0 uident, doc (showString ":"), prt 0 e_])

instance Print (E.Abs.S' a) where
  prt i = \case
    E.Abs.SE _ e_ -> prPrec i 0 (concatD [prt 0 e_])
    E.Abs.If _ e_ s1 s2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 e_, doc (showString "then"), prt 0 s1, doc (showString "else"), prt 0 s2, doc (showString "end")])
    E.Abs.While _ e_ s -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 e_, doc (showString ")"), prt 0 s])
    E.Abs.Return _ e_ -> prPrec i 0 (concatD [doc (showString "return"), prt 0 e_])
    E.Abs.Do _ ss -> prPrec i 0 (concatD [doc (showString "{"), prt 0 ss, doc (showString "}")])
    E.Abs.Case _ e_ cases -> prPrec i 0 (concatD [doc (showString "case"), prt 0 e_, doc (showString "of"), doc (showString "{"), prt 0 cases, doc (showString "}")])
    E.Abs.Break _ -> prPrec i 0 (concatD [doc (showString "break")])
    E.Abs.Continue _ -> prPrec i 0 (concatD [doc (showString "continue")])
    E.Abs.For _ s1 e_ s2 s3 -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 s1, doc (showString ";"), prt 0 e_, doc (showString ";"), prt 0 s2, doc (showString ")"), prt 0 s3])
    E.Abs.Declare _ varbinds -> prPrec i 0 (concatD [doc (showString "var"), prt 0 varbinds])

instance Print [E.Abs.S' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [E.Abs.CASE' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print (E.Abs.CASE' a) where
  prt i = \case
    E.Abs.C _ e_ s -> prPrec i 0 (concatD [prt 0 e_, doc (showString "=>"), prt 0 s])

instance Print [E.Abs.VarBind' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (E.Abs.VarBind' a) where
  prt i = \case
    E.Abs.JustVar _ id_ -> prPrec i 0 (concatD [prt 0 id_])
    E.Abs.VarIs _ id_ e_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 e_])

instance Print (E.Abs.E' a) where
  prt i = \case
    E.Abs.EmptyTuple _ -> prPrec i 13 (concatD [doc (showString "("), doc (showString ")")])
    E.Abs.Tuple _ e_ es -> prPrec i 13 (concatD [doc (showString "("), prt 0 e_, doc (showString ","), prt 0 es, doc (showString ")")])
    E.Abs.HexInt _ hexinteger -> prPrec i 13 (concatD [prt 0 hexinteger])
    E.Abs.Int _ n -> prPrec i 13 (concatD [prt 0 n])
    E.Abs.Var _ id_ -> prPrec i 13 (concatD [prt 0 id_])
    E.Abs.String _ str -> prPrec i 13 (concatD [printString str])
    E.Abs.ConRecord _ uident efields -> prPrec i 13 (concatD [prt 0 uident, doc (showString "{"), prt 0 efields, doc (showString "}")])
    E.Abs.Con _ uident -> prPrec i 13 (concatD [prt 0 uident])
    E.Abs.Wild _ -> prPrec i 13 (concatD [doc (showString "_")])
    E.Abs.PlusPlusPost _ e_ -> prPrec i 12 (concatD [prt 12 e_, doc (showString "++")])
    E.Abs.MinusMinusPost _ e_ -> prPrec i 12 (concatD [prt 12 e_, doc (showString "--")])
    E.Abs.Index _ e_1 e_2 -> prPrec i 12 (concatD [prt 12 e_1, doc (showString "["), prt 0 e_2, doc (showString "]")])
    E.Abs.Dot _ e_ id_ -> prPrec i 12 (concatD [prt 12 e_, doc (showString "."), prt 0 id_])
    E.Abs.Bang _ e_1 e_2 -> prPrec i 12 (concatD [prt 12 e_1, doc (showString "!"), prt 13 e_2])
    E.Abs.Arrow _ e_ id_ -> prPrec i 12 (concatD [prt 12 e_, doc (showString "->"), prt 0 id_])
    E.Abs.App _ e_1 e_2 -> prPrec i 12 (concatD [prt 12 e_1, prt 13 e_2])
    E.Abs.PlusPlusPre _ e_ -> prPrec i 11 (concatD [doc (showString "++"), prt 11 e_])
    E.Abs.MinusMinusPre _ e_ -> prPrec i 11 (concatD [doc (showString "--"), prt 11 e_])
    E.Abs.Negate _ e_ -> prPrec i 11 (concatD [doc (showString "-"), prt 11 e_])
    E.Abs.Not _ e_ -> prPrec i 11 (concatD [doc (showString "!"), prt 11 e_])
    E.Abs.BitwiseNot _ e_ -> prPrec i 11 (concatD [doc (showString "~"), prt 11 e_])
    E.Abs.Deref _ e_ -> prPrec i 11 (concatD [doc (showString "*"), prt 11 e_])
    E.Abs.AddressOf _ e_ -> prPrec i 11 (concatD [doc (showString "&"), prt 11 e_])
    E.Abs.Mul _ e_1 e_2 -> prPrec i 10 (concatD [prt 10 e_1, doc (showString "*"), prt 11 e_2])
    E.Abs.Div _ e_1 e_2 -> prPrec i 10 (concatD [prt 10 e_1, doc (showString "/"), prt 11 e_2])
    E.Abs.Mod _ e_1 e_2 -> prPrec i 10 (concatD [prt 10 e_1, doc (showString "%"), prt 11 e_2])
    E.Abs.Plus _ e_1 e_2 -> prPrec i 9 (concatD [prt 9 e_1, doc (showString "+"), prt 10 e_2])
    E.Abs.Minus _ e_1 e_2 -> prPrec i 9 (concatD [prt 9 e_1, doc (showString "-"), prt 10 e_2])
    E.Abs.Shl _ e_1 e_2 -> prPrec i 8 (concatD [prt 8 e_1, doc (showString "<<"), prt 9 e_2])
    E.Abs.Shr _ e_1 e_2 -> prPrec i 8 (concatD [prt 8 e_1, doc (showString ">>"), prt 9 e_2])
    E.Abs.MyLT _ e_1 e_2 -> prPrec i 7 (concatD [prt 7 e_1, doc (showString "<"), prt 8 e_2])
    E.Abs.LTE _ e_1 e_2 -> prPrec i 7 (concatD [prt 7 e_1, doc (showString "<="), prt 8 e_2])
    E.Abs.MyGT _ e_1 e_2 -> prPrec i 7 (concatD [prt 7 e_1, doc (showString ">"), prt 8 e_2])
    E.Abs.GTE _ e_1 e_2 -> prPrec i 7 (concatD [prt 7 e_1, doc (showString ">="), prt 8 e_2])
    E.Abs.Eq _ e_1 e_2 -> prPrec i 6 (concatD [prt 6 e_1, doc (showString "=="), prt 7 e_2])
    E.Abs.NEq _ e_1 e_2 -> prPrec i 6 (concatD [prt 6 e_1, doc (showString "!="), prt 7 e_2])
    E.Abs.BitwiseAnd _ e_1 e_2 -> prPrec i 5 (concatD [prt 5 e_1, doc (showString "&"), prt 6 e_2])
    E.Abs.BitwiseXor _ e_1 e_2 -> prPrec i 4 (concatD [prt 4 e_1, doc (showString "^"), prt 5 e_2])
    E.Abs.BitwiseOr _ e_1 e_2 -> prPrec i 3 (concatD [prt 3 e_1, doc (showString "|"), prt 4 e_2])
    E.Abs.And _ e_1 e_2 -> prPrec i 2 (concatD [prt 2 e_1, doc (showString "&&"), prt 3 e_2])
    E.Abs.Or _ e_1 e_2 -> prPrec i 1 (concatD [prt 1 e_1, doc (showString "||"), prt 2 e_2])
    E.Abs.Assign _ e_1 aop e_2 -> prPrec i 0 (concatD [prt 1 e_1, prt 0 aop, prt 0 e_2])
    E.Abs.TypeAnnot _ e_ t -> prPrec i 0 (concatD [prt 1 e_, doc (showString "::"), prt 0 t])

instance Print [E.Abs.E' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [E.Abs.EField' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (E.Abs.EField' a) where
  prt i = \case
    E.Abs.EField _ id_ e_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 e_])

instance Print (E.Abs.AOp' a) where
  prt i = \case
    E.Abs.EqEq _ -> prPrec i 0 (concatD [doc (showString "=")])
    E.Abs.PlusEq _ -> prPrec i 0 (concatD [doc (showString "+=")])
    E.Abs.MinusEq _ -> prPrec i 0 (concatD [doc (showString "-=")])
    E.Abs.MulEq _ -> prPrec i 0 (concatD [doc (showString "*=")])
    E.Abs.DivEq _ -> prPrec i 0 (concatD [doc (showString "/=")])
    E.Abs.ModEq _ -> prPrec i 0 (concatD [doc (showString "%=")])
    E.Abs.ShlEq _ -> prPrec i 0 (concatD [doc (showString "<<=")])
    E.Abs.ShrEq _ -> prPrec i 0 (concatD [doc (showString ">>=")])
    E.Abs.AndEq _ -> prPrec i 0 (concatD [doc (showString "&=")])
    E.Abs.XorEq _ -> prPrec i 0 (concatD [doc (showString "^=")])
    E.Abs.OrEq _ -> prPrec i 0 (concatD [doc (showString "|=")])

instance Print (E.Abs.T' a) where
  prt i = \case
    E.Abs.TArrow _ t1 t2 -> prPrec i 0 (concatD [prt 1 t1, doc (showString "->"), prt 0 t2])
    E.Abs.TVar _ id_ -> prPrec i 2 (concatD [prt 0 id_])
    E.Abs.TNat _ n -> prPrec i 2 (concatD [prt 0 n])
    E.Abs.TCon _ uident -> prPrec i 2 (concatD [prt 0 uident])
    E.Abs.TEmptyTup _ -> prPrec i 2 (concatD [doc (showString "("), doc (showString ")")])
    E.Abs.TTup _ t ts -> prPrec i 2 (concatD [doc (showString "("), prt 0 t, doc (showString ","), prt 0 ts, doc (showString ")")])
    E.Abs.TApp _ t1 t2 -> prPrec i 1 (concatD [prt 1 t1, prt 2 t2])
    E.Abs.TArray _ t1 t2 -> prPrec i 0 (concatD [prt 1 t1, doc (showString "["), prt 0 t2, doc (showString "]")])

instance Print [E.Abs.T' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]
