module E.Skel where

-- Haskell module generated by the BNF converter

import E.Abs
import E.ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transUIdent :: UIdent -> Result
transUIdent x = case x of
  UIdent string -> failure x
transInfix :: Infix -> Result
transInfix x = case x of
  Infix string -> failure x
transHexInteger :: HexInteger -> Result
transHexInteger x = case x of
  HexInteger string -> failure x
transM :: M -> Result
transM x = case x of
  Module ds -> failure x
transD :: D -> Result
transD x = case x of
  Defun ident e s -> failure x
  TySig ident t -> failure x
  KindSig uident t -> failure x
  TySyn conargs t -> failure x
  Import modulename -> failure x
  Global globalregion varbind -> failure x
  Data conargs datarhs -> failure x
  StaticData ident e -> failure x
transConArgs :: ConArgs -> Result
transConArgs x = case x of
  CANil uident -> failure x
  CACons conargs ident -> failure x
transModuleName :: ModuleName -> Result
transModuleName x = case x of
  MNil uident -> failure x
  MCons uident modulename -> failure x
transGlobalRegion :: GlobalRegion -> Result
transGlobalRegion x = case x of
  Memory -> failure x
  Storage -> failure x
  TStorage -> failure x
transDataRHS :: DataRHS -> Result
transDataRHS x = case x of
  Boxed unboxedrhs ident -> failure x
  Unboxed unboxedrhs -> failure x
transUnboxedRHS :: UnboxedRHS -> Result
transUnboxedRHS x = case x of
  URHS datacons -> failure x
transDataCon :: DataCon -> Result
transDataCon x = case x of
  DCArgs dca -> failure x
  DCRecord uident recordfields -> failure x
transDCA :: DCA -> Result
transDCA x = case x of
  DCANil uident -> failure x
  DCACons dca t -> failure x
transRecordField :: RecordField -> Result
transRecordField x = case x of
  RF ident t -> failure x
transS :: S -> Result
transS x = case x of
  SE e -> failure x
  If e s1 s2 -> failure x
  While e s -> failure x
  Return e -> failure x
  Do ss -> failure x
  Case e cases -> failure x
  Break -> failure x
  Continue -> failure x
  For s1 e s2 s3 -> failure x
  Declare varbinds -> failure x
transCASE :: CASE -> Result
transCASE x = case x of
  C e s -> failure x
transVarBind :: VarBind -> Result
transVarBind x = case x of
  JustVar ident -> failure x
  VarIs ident e -> failure x
transE :: E -> Result
transE x = case x of
  EmptyTuple -> failure x
  Tuple e es -> failure x
  HexInt hexinteger -> failure x
  Int integer -> failure x
  Var ident -> failure x
  String string -> failure x
  Con uident -> failure x
  Wild -> failure x
  PlusPlusPost e -> failure x
  MinusMinusPost e -> failure x
  Index e1 e2 -> failure x
  Dot e ident -> failure x
  Arrow e ident -> failure x
  App e1 e2 -> failure x
  PlusPlusPre e -> failure x
  MinusMinusPre e -> failure x
  Negate e -> failure x
  Not e -> failure x
  BitwiseNot e -> failure x
  Deref e -> failure x
  AddressOf e -> failure x
  Mul e1 e2 -> failure x
  Div e1 e2 -> failure x
  Mod e1 e2 -> failure x
  Plus e1 e2 -> failure x
  Minus e1 e2 -> failure x
  Shl e1 e2 -> failure x
  Shr e1 e2 -> failure x
  MyLT e1 e2 -> failure x
  LTE e1 e2 -> failure x
  MyGT e1 e2 -> failure x
  GTE e1 e2 -> failure x
  Eq e1 e2 -> failure x
  NEq e1 e2 -> failure x
  BitwiseAnd e1 e2 -> failure x
  BitwiseXor e1 e2 -> failure x
  BitwiseOr e1 e2 -> failure x
  And e1 e2 -> failure x
  Or e1 e2 -> failure x
  Assign e1 aop e2 -> failure x
  TypeAnnot e t -> failure x
transAOp :: AOp -> Result
transAOp x = case x of
  EqEq -> failure x
  PlusEq -> failure x
  MinusEq -> failure x
  MulEq -> failure x
  DivEq -> failure x
  ModEq -> failure x
  ShlEq -> failure x
  ShrEq -> failure x
  AndEq -> failure x
  XorEq -> failure x
  OrEq -> failure x
transT :: T -> Result
transT x = case x of
  TArrow t1 t2 -> failure x
  TVar ident -> failure x
  TNat integer -> failure x
  TCon uident -> failure x
  TEmptyTup -> failure x
  TTup t ts -> failure x
  TApp t1 t2 -> failure x
  TArray t1 t2 -> failure x

