-- File generated by the BNF Converter (bnfc 2.9.6.3).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module E.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified E.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: E.Abs.Ident -> Result
transIdent x = case x of
  E.Abs.Ident string -> failure x

transUIdent :: E.Abs.UIdent -> Result
transUIdent x = case x of
  E.Abs.UIdent string -> failure x

transInfix :: E.Abs.Infix -> Result
transInfix x = case x of
  E.Abs.Infix string -> failure x

transHexInteger :: E.Abs.HexInteger -> Result
transHexInteger x = case x of
  E.Abs.HexInteger string -> failure x

transM :: Show a => E.Abs.M' a -> Result
transM x = case x of
  E.Abs.Module _ ds -> failure x

transD :: Show a => E.Abs.D' a -> Result
transD x = case x of
  E.Abs.Default _ uident t -> failure x
  E.Abs.Defun _ ident e s -> failure x
  E.Abs.Instance _ ident t e s -> failure x
  E.Abs.TySig _ ident t -> failure x
  E.Abs.KindSig _ uident t -> failure x
  E.Abs.TySyn _ conargs t -> failure x
  E.Abs.Import _ modulename -> failure x
  E.Abs.Global _ globalregion varbind -> failure x
  E.Abs.Data _ conargs datarhs -> failure x
  E.Abs.Tag _ conargs t contags -> failure x
  E.Abs.Contract _ ident ds -> failure x

transConArgs :: Show a => E.Abs.ConArgs' a -> Result
transConArgs x = case x of
  E.Abs.CANil _ uident -> failure x
  E.Abs.CACons _ conargs ident -> failure x

transModuleName :: Show a => E.Abs.ModuleName' a -> Result
transModuleName x = case x of
  E.Abs.MNil _ uident -> failure x
  E.Abs.MCons _ uident modulename -> failure x

transGlobalRegion :: Show a => E.Abs.GlobalRegion' a -> Result
transGlobalRegion x = case x of
  E.Abs.Memory _ -> failure x
  E.Abs.Storage _ -> failure x
  E.Abs.TStorage _ -> failure x
  E.Abs.Code _ -> failure x

transDataRHS :: Show a => E.Abs.DataRHS' a -> Result
transDataRHS x = case x of
  E.Abs.Boxed _ unboxedrhs ident -> failure x
  E.Abs.Unboxed _ unboxedrhs -> failure x

transUnboxedRHS :: Show a => E.Abs.UnboxedRHS' a -> Result
transUnboxedRHS x = case x of
  E.Abs.URHS _ datacons -> failure x

transDataCon :: Show a => E.Abs.DataCon' a -> Result
transDataCon x = case x of
  E.Abs.DCArgs _ dca -> failure x
  E.Abs.DCRecord _ uident recordfields -> failure x

transDCA :: Show a => E.Abs.DCA' a -> Result
transDCA x = case x of
  E.Abs.DCANil _ uident -> failure x
  E.Abs.DCACons _ dca t -> failure x

transRecordField :: Show a => E.Abs.RecordField' a -> Result
transRecordField x = case x of
  E.Abs.RF _ ident t -> failure x

transConTag :: Show a => E.Abs.ConTag' a -> Result
transConTag x = case x of
  E.Abs.ConTag _ uident e -> failure x

transS :: Show a => E.Abs.S' a -> Result
transS x = case x of
  E.Abs.SE _ e -> failure x
  E.Abs.If _ e s1 s2 -> failure x
  E.Abs.While _ e s -> failure x
  E.Abs.Return _ e -> failure x
  E.Abs.Do _ ss -> failure x
  E.Abs.Case _ e cases -> failure x
  E.Abs.Break _ -> failure x
  E.Abs.Continue _ -> failure x
  E.Abs.For _ s1 e s2 s3 -> failure x
  E.Abs.Declare _ varbinds -> failure x

transCASE :: Show a => E.Abs.CASE' a -> Result
transCASE x = case x of
  E.Abs.C _ e s -> failure x

transVarBind :: Show a => E.Abs.VarBind' a -> Result
transVarBind x = case x of
  E.Abs.JustVar _ ident -> failure x
  E.Abs.VarIs _ ident e -> failure x

transE :: Show a => E.Abs.E' a -> Result
transE x = case x of
  E.Abs.EmptyTuple _ -> failure x
  E.Abs.Tuple _ e es -> failure x
  E.Abs.HexInt _ hexinteger -> failure x
  E.Abs.Int _ integer -> failure x
  E.Abs.Var _ ident -> failure x
  E.Abs.String _ string -> failure x
  E.Abs.ConRecord _ uident efields -> failure x
  E.Abs.Con _ uident -> failure x
  E.Abs.Wild _ -> failure x
  E.Abs.PlusPlusPost _ e -> failure x
  E.Abs.MinusMinusPost _ e -> failure x
  E.Abs.Index _ e1 e2 -> failure x
  E.Abs.Dot _ e ident -> failure x
  E.Abs.Bang _ e1 e2 -> failure x
  E.Abs.Arrow _ e ident -> failure x
  E.Abs.App _ e1 e2 -> failure x
  E.Abs.PlusPlusPre _ e -> failure x
  E.Abs.MinusMinusPre _ e -> failure x
  E.Abs.Negate _ e -> failure x
  E.Abs.Not _ e -> failure x
  E.Abs.BitwiseNot _ e -> failure x
  E.Abs.Deref _ e -> failure x
  E.Abs.AddressOf _ e -> failure x
  E.Abs.Mul _ e1 e2 -> failure x
  E.Abs.Div _ e1 e2 -> failure x
  E.Abs.Mod _ e1 e2 -> failure x
  E.Abs.Plus _ e1 e2 -> failure x
  E.Abs.Minus _ e1 e2 -> failure x
  E.Abs.Shl _ e1 e2 -> failure x
  E.Abs.Shr _ e1 e2 -> failure x
  E.Abs.MyLT _ e1 e2 -> failure x
  E.Abs.LTE _ e1 e2 -> failure x
  E.Abs.MyGT _ e1 e2 -> failure x
  E.Abs.GTE _ e1 e2 -> failure x
  E.Abs.Eq _ e1 e2 -> failure x
  E.Abs.NEq _ e1 e2 -> failure x
  E.Abs.BitwiseAnd _ e1 e2 -> failure x
  E.Abs.BitwiseXor _ e1 e2 -> failure x
  E.Abs.BitwiseOr _ e1 e2 -> failure x
  E.Abs.And _ e1 e2 -> failure x
  E.Abs.Or _ e1 e2 -> failure x
  E.Abs.Assign _ e1 aop e2 -> failure x
  E.Abs.TypeAnnot _ e t -> failure x

transEField :: Show a => E.Abs.EField' a -> Result
transEField x = case x of
  E.Abs.EField _ ident e -> failure x

transAOp :: Show a => E.Abs.AOp' a -> Result
transAOp x = case x of
  E.Abs.EqEq _ -> failure x
  E.Abs.PlusEq _ -> failure x
  E.Abs.MinusEq _ -> failure x
  E.Abs.MulEq _ -> failure x
  E.Abs.DivEq _ -> failure x
  E.Abs.ModEq _ -> failure x
  E.Abs.ShlEq _ -> failure x
  E.Abs.ShrEq _ -> failure x
  E.Abs.AndEq _ -> failure x
  E.Abs.XorEq _ -> failure x
  E.Abs.OrEq _ -> failure x

transT :: Show a => E.Abs.T' a -> Result
transT x = case x of
  E.Abs.TArrow _ t1 t2 -> failure x
  E.Abs.TVar _ ident -> failure x
  E.Abs.TNat _ integer -> failure x
  E.Abs.TCon _ uident -> failure x
  E.Abs.TEmptyTup _ -> failure x
  E.Abs.TTup _ t ts -> failure x
  E.Abs.TApp _ t1 t2 -> failure x
  E.Abs.TArray _ t1 t2 -> failure x
