-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module E.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified E.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: E.Abs.Ident -> Result
transIdent x = case x of
  E.Abs.Ident string -> failure x

transUIdent :: E.Abs.UIdent -> Result
transUIdent x = case x of
  E.Abs.UIdent string -> failure x

transInfix :: E.Abs.Infix -> Result
transInfix x = case x of
  E.Abs.Infix string -> failure x

transHexInteger :: E.Abs.HexInteger -> Result
transHexInteger x = case x of
  E.Abs.HexInteger string -> failure x

transM :: E.Abs.M -> Result
transM x = case x of
  E.Abs.Module ds -> failure x

transD :: E.Abs.D -> Result
transD x = case x of
  E.Abs.Default uident t -> failure x
  E.Abs.Defun ident e s -> failure x
  E.Abs.Instance ident t e s -> failure x
  E.Abs.TySig ident t -> failure x
  E.Abs.KindSig uident t -> failure x
  E.Abs.TySyn conargs t -> failure x
  E.Abs.Import modulename -> failure x
  E.Abs.Global globalregion varbind -> failure x
  E.Abs.Data conargs datarhs -> failure x
  E.Abs.Tag conargs t contags -> failure x

transConArgs :: E.Abs.ConArgs -> Result
transConArgs x = case x of
  E.Abs.CANil uident -> failure x
  E.Abs.CACons conargs ident -> failure x

transModuleName :: E.Abs.ModuleName -> Result
transModuleName x = case x of
  E.Abs.MNil uident -> failure x
  E.Abs.MCons uident modulename -> failure x

transGlobalRegion :: E.Abs.GlobalRegion -> Result
transGlobalRegion x = case x of
  E.Abs.Memory -> failure x
  E.Abs.Storage -> failure x
  E.Abs.TStorage -> failure x
  E.Abs.Code -> failure x

transDataRHS :: E.Abs.DataRHS -> Result
transDataRHS x = case x of
  E.Abs.Boxed unboxedrhs ident -> failure x
  E.Abs.Unboxed unboxedrhs -> failure x

transUnboxedRHS :: E.Abs.UnboxedRHS -> Result
transUnboxedRHS x = case x of
  E.Abs.URHS datacons -> failure x

transDataCon :: E.Abs.DataCon -> Result
transDataCon x = case x of
  E.Abs.DCArgs dca -> failure x
  E.Abs.DCRecord uident recordfields -> failure x

transDCA :: E.Abs.DCA -> Result
transDCA x = case x of
  E.Abs.DCANil uident -> failure x
  E.Abs.DCACons dca t -> failure x

transRecordField :: E.Abs.RecordField -> Result
transRecordField x = case x of
  E.Abs.RF ident t -> failure x

transConTag :: E.Abs.ConTag -> Result
transConTag x = case x of
  E.Abs.ConTag uident e -> failure x

transS :: E.Abs.S -> Result
transS x = case x of
  E.Abs.SE e -> failure x
  E.Abs.If e s1 s2 -> failure x
  E.Abs.While e s -> failure x
  E.Abs.Return e -> failure x
  E.Abs.Do ss -> failure x
  E.Abs.Case e cases -> failure x
  E.Abs.Break -> failure x
  E.Abs.Continue -> failure x
  E.Abs.For s1 e s2 s3 -> failure x
  E.Abs.Declare varbinds -> failure x

transCASE :: E.Abs.CASE -> Result
transCASE x = case x of
  E.Abs.C e s -> failure x

transVarBind :: E.Abs.VarBind -> Result
transVarBind x = case x of
  E.Abs.JustVar ident -> failure x
  E.Abs.VarIs ident e -> failure x

transE :: E.Abs.E -> Result
transE x = case x of
  E.Abs.EmptyTuple -> failure x
  E.Abs.Tuple e es -> failure x
  E.Abs.HexInt hexinteger -> failure x
  E.Abs.Int integer -> failure x
  E.Abs.Var ident -> failure x
  E.Abs.String string -> failure x
  E.Abs.ConRecord uident efields -> failure x
  E.Abs.Con uident -> failure x
  E.Abs.Wild -> failure x
  E.Abs.PlusPlusPost e -> failure x
  E.Abs.MinusMinusPost e -> failure x
  E.Abs.Index e1 e2 -> failure x
  E.Abs.Dot e ident -> failure x
  E.Abs.Bang e1 e2 -> failure x
  E.Abs.Arrow e ident -> failure x
  E.Abs.App e1 e2 -> failure x
  E.Abs.PlusPlusPre e -> failure x
  E.Abs.MinusMinusPre e -> failure x
  E.Abs.Negate e -> failure x
  E.Abs.Not e -> failure x
  E.Abs.BitwiseNot e -> failure x
  E.Abs.Deref e -> failure x
  E.Abs.AddressOf e -> failure x
  E.Abs.Mul e1 e2 -> failure x
  E.Abs.Div e1 e2 -> failure x
  E.Abs.Mod e1 e2 -> failure x
  E.Abs.Plus e1 e2 -> failure x
  E.Abs.Minus e1 e2 -> failure x
  E.Abs.Shl e1 e2 -> failure x
  E.Abs.Shr e1 e2 -> failure x
  E.Abs.MyLT e1 e2 -> failure x
  E.Abs.LTE e1 e2 -> failure x
  E.Abs.MyGT e1 e2 -> failure x
  E.Abs.GTE e1 e2 -> failure x
  E.Abs.Eq e1 e2 -> failure x
  E.Abs.NEq e1 e2 -> failure x
  E.Abs.BitwiseAnd e1 e2 -> failure x
  E.Abs.BitwiseXor e1 e2 -> failure x
  E.Abs.BitwiseOr e1 e2 -> failure x
  E.Abs.And e1 e2 -> failure x
  E.Abs.Or e1 e2 -> failure x
  E.Abs.Assign e1 aop e2 -> failure x
  E.Abs.TypeAnnot e t -> failure x

transEField :: E.Abs.EField -> Result
transEField x = case x of
  E.Abs.EField ident e -> failure x

transAOp :: E.Abs.AOp -> Result
transAOp x = case x of
  E.Abs.EqEq -> failure x
  E.Abs.PlusEq -> failure x
  E.Abs.MinusEq -> failure x
  E.Abs.MulEq -> failure x
  E.Abs.DivEq -> failure x
  E.Abs.ModEq -> failure x
  E.Abs.ShlEq -> failure x
  E.Abs.ShrEq -> failure x
  E.Abs.AndEq -> failure x
  E.Abs.XorEq -> failure x
  E.Abs.OrEq -> failure x

transT :: E.Abs.T -> Result
transT x = case x of
  E.Abs.TArrow t1 t2 -> failure x
  E.Abs.TVar ident -> failure x
  E.Abs.TNat integer -> failure x
  E.Abs.TCon uident -> failure x
  E.Abs.TEmptyTup -> failure x
  E.Abs.TTup t ts -> failure x
  E.Abs.TApp t1 t2 -> failure x
  E.Abs.TArray t1 t2 -> failure x
