-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language E.

module AbsE where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data M = Module [D]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data D
    = Default UIdent T
    | Defun Ident E S
    | Instance Ident T E S
    | TySig Ident T
    | KindSig UIdent T
    | TySyn ConArgs T
    | Import ModuleName
    | Global GlobalRegion VarBind
    | Data ConArgs DataRHS
    | Tag ConArgs T [ConTag]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ConArgs = CANil UIdent | CACons ConArgs Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ModuleName = MNil UIdent | MCons UIdent ModuleName
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data GlobalRegion = Memory | Storage | TStorage | Code
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data DataRHS = Boxed UnboxedRHS Ident | Unboxed UnboxedRHS
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data UnboxedRHS = URHS [DataCon]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data DataCon = DCArgs DCA | DCRecord UIdent [RecordField]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data DCA = DCANil UIdent | DCACons DCA T
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RecordField = RF Ident T
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ConTag = ConTag UIdent E
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data S
    = SE E
    | If E S S
    | While E S
    | Return E
    | Do [S]
    | Case E [CASE]
    | Break
    | Continue
    | For S E S S
    | Declare [VarBind]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data CASE = C E S
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data VarBind = JustVar Ident | VarIs Ident E
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data E
    = EmptyTuple
    | Tuple E [E]
    | HexInt HexInteger
    | Int Integer
    | Var Ident
    | String String
    | ConRecord UIdent [EField]
    | Con UIdent
    | Wild
    | PlusPlusPost E
    | MinusMinusPost E
    | Index E E
    | Dot E Ident
    | Bang E E
    | Arrow E Ident
    | App E E
    | PlusPlusPre E
    | MinusMinusPre E
    | Negate E
    | Not E
    | BitwiseNot E
    | Deref E
    | AddressOf E
    | Mul E E
    | Div E E
    | Mod E E
    | Plus E E
    | Minus E E
    | Shl E E
    | Shr E E
    | MyLT E E
    | LTE E E
    | MyGT E E
    | GTE E E
    | Eq E E
    | NEq E E
    | BitwiseAnd E E
    | BitwiseXor E E
    | BitwiseOr E E
    | And E E
    | Or E E
    | Assign E AOp E
    | TypeAnnot E T
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data EField = EField Ident E
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data AOp
    = EqEq
    | PlusEq
    | MinusEq
    | MulEq
    | DivEq
    | ModEq
    | ShlEq
    | ShrEq
    | AndEq
    | XorEq
    | OrEq
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data T
    = TArrow T T
    | TVar Ident
    | TNat Integer
    | TCon UIdent
    | TEmptyTup
    | TTup T [T]
    | TApp T T
    | TArray T T
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype UIdent = UIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype Infix = Infix String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype HexInteger = HexInteger String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

