-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.5).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module ParE
  ( happyError
  , myLexer
  , pM
  , pListD
  , pD
  , pConArgs
  , pModuleName
  , pGlobalRegion
  , pDataRHS
  , pUnboxedRHS
  , pListDataCon
  , pDataCon
  , pDCA
  , pListRecordField
  , pRecordField
  , pListConTag
  , pConTag
  , pS
  , pListS
  , pListCASE
  , pCASE
  , pListVarBind
  , pVarBind
  , pE13
  , pListE
  , pListEField
  , pEField
  , pE12
  , pE11
  , pE10
  , pE9
  , pE8
  , pE7
  , pE6
  , pE5
  , pE4
  , pE3
  , pE2
  , pE1
  , pE
  , pAOp
  , pT
  , pT2
  , pListT
  , pT1
  ) where

import Prelude

import qualified AbsE
import LexE

}

%name pM M
%name pListD ListD
%name pD D
%name pConArgs ConArgs
%name pModuleName ModuleName
%name pGlobalRegion GlobalRegion
%name pDataRHS DataRHS
%name pUnboxedRHS UnboxedRHS
%name pListDataCon ListDataCon
%name pDataCon DataCon
%name pDCA DCA
%name pListRecordField ListRecordField
%name pRecordField RecordField
%name pListConTag ListConTag
%name pConTag ConTag
%name pS S
%name pListS ListS
%name pListCASE ListCASE
%name pCASE CASE
%name pListVarBind ListVarBind
%name pVarBind VarBind
%name pE13 E13
%name pListE ListE
%name pListEField ListEField
%name pEField EField
%name pE12 E12
%name pE11 E11
%name pE10 E10
%name pE9 E9
%name pE8 E8
%name pE7 E7
%name pE6 E6
%name pE5 E5
%name pE4 E4
%name pE3 E3
%name pE2 E2
%name pE1 E1
%name pE E
%name pAOp AOp
%name pT T
%name pT2 T2
%name pListT ListT
%name pT1 T1
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '!'          { PT _ (TS _ 1)          }
  '!='         { PT _ (TS _ 2)          }
  '%'          { PT _ (TS _ 3)          }
  '%='         { PT _ (TS _ 4)          }
  '&'          { PT _ (TS _ 5)          }
  '&&'         { PT _ (TS _ 6)          }
  '&='         { PT _ (TS _ 7)          }
  '('          { PT _ (TS _ 8)          }
  ')'          { PT _ (TS _ 9)          }
  '*'          { PT _ (TS _ 10)         }
  '*='         { PT _ (TS _ 11)         }
  '+'          { PT _ (TS _ 12)         }
  '++'         { PT _ (TS _ 13)         }
  '+='         { PT _ (TS _ 14)         }
  ','          { PT _ (TS _ 15)         }
  '-'          { PT _ (TS _ 16)         }
  '--'         { PT _ (TS _ 17)         }
  '-='         { PT _ (TS _ 18)         }
  '->'         { PT _ (TS _ 19)         }
  '.'          { PT _ (TS _ 20)         }
  '/'          { PT _ (TS _ 21)         }
  '/='         { PT _ (TS _ 22)         }
  ':'          { PT _ (TS _ 23)         }
  '::'         { PT _ (TS _ 24)         }
  ':='         { PT _ (TS _ 25)         }
  ';'          { PT _ (TS _ 26)         }
  '<'          { PT _ (TS _ 27)         }
  '<<'         { PT _ (TS _ 28)         }
  '<<='        { PT _ (TS _ 29)         }
  '<='         { PT _ (TS _ 30)         }
  '='          { PT _ (TS _ 31)         }
  '=='         { PT _ (TS _ 32)         }
  '=>'         { PT _ (TS _ 33)         }
  '>'          { PT _ (TS _ 34)         }
  '>='         { PT _ (TS _ 35)         }
  '>>'         { PT _ (TS _ 36)         }
  '>>='        { PT _ (TS _ 37)         }
  '['          { PT _ (TS _ 38)         }
  ']'          { PT _ (TS _ 39)         }
  '^'          { PT _ (TS _ 40)         }
  '^='         { PT _ (TS _ 41)         }
  '_'          { PT _ (TS _ 42)         }
  'break'      { PT _ (TS _ 43)         }
  'case'       { PT _ (TS _ 44)         }
  'code'       { PT _ (TS _ 45)         }
  'continue'   { PT _ (TS _ 46)         }
  'data'       { PT _ (TS _ 47)         }
  'default'    { PT _ (TS _ 48)         }
  'else'       { PT _ (TS _ 49)         }
  'end'        { PT _ (TS _ 50)         }
  'for'        { PT _ (TS _ 51)         }
  'if'         { PT _ (TS _ 52)         }
  'import'     { PT _ (TS _ 53)         }
  'instance'   { PT _ (TS _ 54)         }
  'memory'     { PT _ (TS _ 55)         }
  'of'         { PT _ (TS _ 56)         }
  'region'     { PT _ (TS _ 57)         }
  'return'     { PT _ (TS _ 58)         }
  'storage'    { PT _ (TS _ 59)         }
  'tag'        { PT _ (TS _ 60)         }
  'then'       { PT _ (TS _ 61)         }
  'tstorage'   { PT _ (TS _ 62)         }
  'type'       { PT _ (TS _ 63)         }
  'var'        { PT _ (TS _ 64)         }
  'where'      { PT _ (TS _ 65)         }
  'while'      { PT _ (TS _ 66)         }
  '{'          { PT _ (TS _ 67)         }
  '|'          { PT _ (TS _ 68)         }
  '|='         { PT _ (TS _ 69)         }
  '||'         { PT _ (TS _ 70)         }
  '}'          { PT _ (TS _ 71)         }
  '~'          { PT _ (TS _ 72)         }
  L_Ident      { PT _ (TV $$)           }
  L_integ      { PT _ (TI $$)           }
  L_quoted     { PT _ (TL $$)           }
  L_UIdent     { PT _ (T_UIdent $$)     }
  L_Infix      { PT _ (T_Infix $$)      }
  L_HexInteger { PT _ (T_HexInteger $$) }

%%

Ident :: { AbsE.Ident }
Ident  : L_Ident { AbsE.Ident $1 }

Integer :: { Integer }
Integer  : L_integ  { (read $1) :: Integer }

String  :: { String }
String   : L_quoted { $1 }

UIdent :: { AbsE.UIdent }
UIdent  : L_UIdent { AbsE.UIdent $1 }

Infix :: { AbsE.Infix }
Infix  : L_Infix { AbsE.Infix $1 }

HexInteger :: { AbsE.HexInteger }
HexInteger  : L_HexInteger { AbsE.HexInteger $1 }

M :: { AbsE.M }
M : ListD { AbsE.Module $1 }

ListD :: { [AbsE.D] }
ListD
  : {- empty -} { [] } | D { (:[]) $1 } | D ';' ListD { (:) $1 $3 }

D :: { AbsE.D }
D : 'default' UIdent '=' T { AbsE.Default $2 $4 }
  | Ident E13 ':=' S { AbsE.Defun $1 $2 $4 }
  | 'instance' Ident ':' T 'where' E13 ':=' S { AbsE.Instance $2 $4 $6 $8 }
  | Ident ':' T { AbsE.TySig $1 $3 }
  | UIdent ':' T { AbsE.KindSig $1 $3 }
  | 'type' ConArgs '=' T { AbsE.TySyn $2 $4 }
  | 'import' ModuleName { AbsE.Import $2 }
  | GlobalRegion VarBind { AbsE.Global $1 $2 }
  | 'data' ConArgs '=' DataRHS { AbsE.Data $2 $4 }
  | 'tag' ConArgs '=' T 'where' '{' ListConTag '}' { AbsE.Tag $2 $4 $7 }

ConArgs :: { AbsE.ConArgs }
ConArgs
  : UIdent { AbsE.CANil $1 } | ConArgs Ident { AbsE.CACons $1 $2 }

ModuleName :: { AbsE.ModuleName }
ModuleName
  : UIdent { AbsE.MNil $1 }
  | UIdent '.' ModuleName { AbsE.MCons $1 $3 }

GlobalRegion :: { AbsE.GlobalRegion }
GlobalRegion
  : 'memory' { AbsE.Memory }
  | 'storage' { AbsE.Storage }
  | 'tstorage' { AbsE.TStorage }
  | 'code' { AbsE.Code }

DataRHS :: { AbsE.DataRHS }
DataRHS
  : UnboxedRHS 'region' Ident { AbsE.Boxed $1 $3 }
  | UnboxedRHS { AbsE.Unboxed $1 }

UnboxedRHS :: { AbsE.UnboxedRHS }
UnboxedRHS : '{' ListDataCon '}' { AbsE.URHS $2 }

ListDataCon :: { [AbsE.DataCon] }
ListDataCon
  : {- empty -} { [] }
  | DataCon { (:[]) $1 }
  | DataCon ';' ListDataCon { (:) $1 $3 }

DataCon :: { AbsE.DataCon }
DataCon
  : DCA { AbsE.DCArgs $1 }
  | UIdent '{' ListRecordField '}' { AbsE.DCRecord $1 $3 }

DCA :: { AbsE.DCA }
DCA : UIdent { AbsE.DCANil $1 } | DCA T2 { AbsE.DCACons $1 $2 }

ListRecordField :: { [AbsE.RecordField] }
ListRecordField
  : {- empty -} { [] }
  | RecordField { (:[]) $1 }
  | RecordField ',' ListRecordField { (:) $1 $3 }

RecordField :: { AbsE.RecordField }
RecordField : Ident ':' T { AbsE.RF $1 $3 }

ListConTag :: { [AbsE.ConTag] }
ListConTag
  : {- empty -} { [] }
  | ConTag { (:[]) $1 }
  | ConTag ',' ListConTag { (:) $1 $3 }

ConTag :: { AbsE.ConTag }
ConTag : UIdent ':' E { AbsE.ConTag $1 $3 }

S :: { AbsE.S }
S : E { AbsE.SE $1 }
  | 'if' E 'then' S 'else' S 'end' { AbsE.If $2 $4 $6 }
  | 'while' '(' E ')' S { AbsE.While $3 $5 }
  | 'return' E { AbsE.Return $2 }
  | '{' ListS '}' { AbsE.Do $2 }
  | 'case' E 'of' '{' ListCASE '}' { AbsE.Case $2 $5 }
  | 'break' { AbsE.Break }
  | 'continue' { AbsE.Continue }
  | 'for' '(' S ';' E ';' S ')' S { AbsE.For $3 $5 $7 $9 }
  | 'var' ListVarBind { AbsE.Declare $2 }

ListS :: { [AbsE.S] }
ListS
  : {- empty -} { [] } | S { (:[]) $1 } | S ';' ListS { (:) $1 $3 }

ListCASE :: { [AbsE.CASE] }
ListCASE
  : {- empty -} { [] }
  | CASE { (:[]) $1 }
  | CASE ';' ListCASE { (:) $1 $3 }

CASE :: { AbsE.CASE }
CASE : E '=>' S { AbsE.C $1 $3 }

ListVarBind :: { [AbsE.VarBind] }
ListVarBind
  : VarBind { (:[]) $1 } | VarBind ',' ListVarBind { (:) $1 $3 }

VarBind :: { AbsE.VarBind }
VarBind
  : Ident { AbsE.JustVar $1 } | Ident '=' E { AbsE.VarIs $1 $3 }

E13 :: { AbsE.E }
E13
  : '(' ')' { AbsE.EmptyTuple }
  | '(' E ',' ListE ')' { AbsE.Tuple $2 $4 }
  | HexInteger { AbsE.HexInt $1 }
  | Integer { AbsE.Int $1 }
  | Ident { AbsE.Var $1 }
  | String { AbsE.String $1 }
  | UIdent '{' ListEField '}' { AbsE.ConRecord $1 $3 }
  | UIdent { AbsE.Con $1 }
  | '_' { AbsE.Wild }
  | '(' E ')' { $2 }

ListE :: { [AbsE.E] }
ListE : E { (:[]) $1 } | E ',' ListE { (:) $1 $3 }

ListEField :: { [AbsE.EField] }
ListEField
  : {- empty -} { [] }
  | EField { (:[]) $1 }
  | EField ',' ListEField { (:) $1 $3 }

EField :: { AbsE.EField }
EField : Ident ':' E { AbsE.EField $1 $3 }

E12 :: { AbsE.E }
E12
  : E12 '++' { AbsE.PlusPlusPost $1 }
  | E12 '--' { AbsE.MinusMinusPost $1 }
  | E12 '[' E ']' { AbsE.Index $1 $3 }
  | E12 '.' Ident { AbsE.Dot $1 $3 }
  | E12 '!' E13 { AbsE.Bang $1 $3 }
  | E12 '->' Ident { AbsE.Arrow $1 $3 }
  | E12 E13 { AbsE.App $1 $2 }
  | E13 { $1 }

E11 :: { AbsE.E }
E11
  : '++' E11 { AbsE.PlusPlusPre $2 }
  | '--' E11 { AbsE.MinusMinusPre $2 }
  | '-' E11 { AbsE.Negate $2 }
  | '!' E11 { AbsE.Not $2 }
  | '~' E11 { AbsE.BitwiseNot $2 }
  | '*' E11 { AbsE.Deref $2 }
  | '&' E11 { AbsE.AddressOf $2 }
  | E12 { $1 }

E10 :: { AbsE.E }
E10
  : E10 '*' E11 { AbsE.Mul $1 $3 }
  | E10 '/' E11 { AbsE.Div $1 $3 }
  | E10 '%' E11 { AbsE.Mod $1 $3 }
  | E11 { $1 }

E9 :: { AbsE.E }
E9
  : E9 '+' E10 { AbsE.Plus $1 $3 }
  | E9 '-' E10 { AbsE.Minus $1 $3 }
  | E10 { $1 }

E8 :: { AbsE.E }
E8
  : E8 '<<' E9 { AbsE.Shl $1 $3 }
  | E8 '>>' E9 { AbsE.Shr $1 $3 }
  | E9 { $1 }

E7 :: { AbsE.E }
E7
  : E7 '<' E8 { AbsE.MyLT $1 $3 }
  | E7 '<=' E8 { AbsE.LTE $1 $3 }
  | E7 '>' E8 { AbsE.MyGT $1 $3 }
  | E7 '>=' E8 { AbsE.GTE $1 $3 }
  | E8 { $1 }

E6 :: { AbsE.E }
E6
  : E6 '==' E7 { AbsE.Eq $1 $3 }
  | E6 '!=' E7 { AbsE.NEq $1 $3 }
  | E7 { $1 }

E5 :: { AbsE.E }
E5 : E5 '&' E6 { AbsE.BitwiseAnd $1 $3 } | E6 { $1 }

E4 :: { AbsE.E }
E4 : E4 '^' E5 { AbsE.BitwiseXor $1 $3 } | E5 { $1 }

E3 :: { AbsE.E }
E3 : E3 '|' E4 { AbsE.BitwiseOr $1 $3 } | E4 { $1 }

E2 :: { AbsE.E }
E2 : E2 '&&' E3 { AbsE.And $1 $3 } | E3 { $1 }

E1 :: { AbsE.E }
E1 : E1 '||' E2 { AbsE.Or $1 $3 } | E2 { $1 }

E :: { AbsE.E }
E : E1 { $1 }
  | E1 AOp E { AbsE.Assign $1 $2 $3 }
  | E1 '::' T { AbsE.TypeAnnot $1 $3 }

AOp :: { AbsE.AOp }
AOp
  : '=' { AbsE.EqEq }
  | '+=' { AbsE.PlusEq }
  | '-=' { AbsE.MinusEq }
  | '*=' { AbsE.MulEq }
  | '/=' { AbsE.DivEq }
  | '%=' { AbsE.ModEq }
  | '<<=' { AbsE.ShlEq }
  | '>>=' { AbsE.ShrEq }
  | '&=' { AbsE.AndEq }
  | '^=' { AbsE.XorEq }
  | '|=' { AbsE.OrEq }

T :: { AbsE.T }
T : T1 '->' T { AbsE.TArrow $1 $3 }
  | T1 '[' T ']' { AbsE.TArray $1 $3 }
  | T1 { $1 }

T2 :: { AbsE.T }
T2
  : Ident { AbsE.TVar $1 }
  | Integer { AbsE.TNat $1 }
  | UIdent { AbsE.TCon $1 }
  | '(' ')' { AbsE.TEmptyTup }
  | '(' T ',' ListT ')' { AbsE.TTup $2 $4 }
  | '(' T ')' { $2 }

ListT :: { [AbsE.T] }
ListT : T { (:[]) $1 } | T ',' ListT { (:) $1 $3 }

T1 :: { AbsE.T }
T1 : T1 T2 { AbsE.TApp $1 $2 } | T2 { $1 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

}

