-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for PrintE.

module PrintE where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsE

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsE.Ident where
  prt _ (AbsE.Ident i) = doc $ showString i
instance Print AbsE.UIdent where
  prt _ (AbsE.UIdent i) = doc $ showString i
instance Print AbsE.Infix where
  prt _ (AbsE.Infix i) = doc $ showString i
instance Print AbsE.HexInteger where
  prt _ (AbsE.HexInteger i) = doc $ showString i
instance Print AbsE.M where
  prt i = \case
    AbsE.Module ds -> prPrec i 0 (concatD [prt 0 ds])

instance Print [AbsE.D] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print AbsE.D where
  prt i = \case
    AbsE.Default uident t -> prPrec i 0 (concatD [doc (showString "default"), prt 0 uident, doc (showString "="), prt 0 t])
    AbsE.Defun id_ e_ s -> prPrec i 0 (concatD [prt 0 id_, prt 13 e_, doc (showString ":="), prt 0 s])
    AbsE.Instance id_ t e_ s -> prPrec i 0 (concatD [doc (showString "instance"), prt 0 id_, doc (showString ":"), prt 0 t, doc (showString "where"), prt 13 e_, doc (showString ":="), prt 0 s])
    AbsE.TySig id_ t -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 t])
    AbsE.KindSig uident t -> prPrec i 0 (concatD [prt 0 uident, doc (showString ":"), prt 0 t])
    AbsE.TySyn conargs t -> prPrec i 0 (concatD [doc (showString "type"), prt 0 conargs, doc (showString "="), prt 0 t])
    AbsE.Import modulename -> prPrec i 0 (concatD [doc (showString "import"), prt 0 modulename])
    AbsE.Global globalregion varbind -> prPrec i 0 (concatD [prt 0 globalregion, prt 0 varbind])
    AbsE.Data conargs datarhs -> prPrec i 0 (concatD [doc (showString "data"), prt 0 conargs, doc (showString "="), prt 0 datarhs])
    AbsE.Tag conargs t contags -> prPrec i 0 (concatD [doc (showString "tag"), prt 0 conargs, doc (showString "="), prt 0 t, doc (showString "where"), doc (showString "{"), prt 0 contags, doc (showString "}")])

instance Print AbsE.ConArgs where
  prt i = \case
    AbsE.CANil uident -> prPrec i 0 (concatD [prt 0 uident])
    AbsE.CACons conargs id_ -> prPrec i 0 (concatD [prt 0 conargs, prt 0 id_])

instance Print AbsE.ModuleName where
  prt i = \case
    AbsE.MNil uident -> prPrec i 0 (concatD [prt 0 uident])
    AbsE.MCons uident modulename -> prPrec i 0 (concatD [prt 0 uident, doc (showString "."), prt 0 modulename])

instance Print AbsE.GlobalRegion where
  prt i = \case
    AbsE.Memory -> prPrec i 0 (concatD [doc (showString "memory")])
    AbsE.Storage -> prPrec i 0 (concatD [doc (showString "storage")])
    AbsE.TStorage -> prPrec i 0 (concatD [doc (showString "tstorage")])
    AbsE.Code -> prPrec i 0 (concatD [doc (showString "code")])

instance Print AbsE.DataRHS where
  prt i = \case
    AbsE.Boxed unboxedrhs id_ -> prPrec i 0 (concatD [prt 0 unboxedrhs, doc (showString "region"), prt 0 id_])
    AbsE.Unboxed unboxedrhs -> prPrec i 0 (concatD [prt 0 unboxedrhs])

instance Print AbsE.UnboxedRHS where
  prt i = \case
    AbsE.URHS datacons -> prPrec i 0 (concatD [doc (showString "{"), prt 0 datacons, doc (showString "}")])

instance Print [AbsE.DataCon] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print AbsE.DataCon where
  prt i = \case
    AbsE.DCArgs dca -> prPrec i 0 (concatD [prt 0 dca])
    AbsE.DCRecord uident recordfields -> prPrec i 0 (concatD [prt 0 uident, doc (showString "{"), prt 0 recordfields, doc (showString "}")])

instance Print AbsE.DCA where
  prt i = \case
    AbsE.DCANil uident -> prPrec i 0 (concatD [prt 0 uident])
    AbsE.DCACons dca t -> prPrec i 0 (concatD [prt 0 dca, prt 2 t])

instance Print [AbsE.RecordField] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsE.RecordField where
  prt i = \case
    AbsE.RF id_ t -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 t])

instance Print [AbsE.ConTag] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsE.ConTag where
  prt i = \case
    AbsE.ConTag uident e_ -> prPrec i 0 (concatD [prt 0 uident, doc (showString ":"), prt 0 e_])

instance Print AbsE.S where
  prt i = \case
    AbsE.SE e_ -> prPrec i 0 (concatD [prt 0 e_])
    AbsE.If e_ s1 s2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 e_, doc (showString "then"), prt 0 s1, doc (showString "else"), prt 0 s2, doc (showString "end")])
    AbsE.While e_ s -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 e_, doc (showString ")"), prt 0 s])
    AbsE.Return e_ -> prPrec i 0 (concatD [doc (showString "return"), prt 0 e_])
    AbsE.Do ss -> prPrec i 0 (concatD [doc (showString "{"), prt 0 ss, doc (showString "}")])
    AbsE.Case e_ cases -> prPrec i 0 (concatD [doc (showString "case"), prt 0 e_, doc (showString "of"), doc (showString "{"), prt 0 cases, doc (showString "}")])
    AbsE.Break -> prPrec i 0 (concatD [doc (showString "break")])
    AbsE.Continue -> prPrec i 0 (concatD [doc (showString "continue")])
    AbsE.For s1 e_ s2 s3 -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 s1, doc (showString ";"), prt 0 e_, doc (showString ";"), prt 0 s2, doc (showString ")"), prt 0 s3])
    AbsE.Declare varbinds -> prPrec i 0 (concatD [doc (showString "var"), prt 0 varbinds])

instance Print [AbsE.S] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [AbsE.CASE] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print AbsE.CASE where
  prt i = \case
    AbsE.C e_ s -> prPrec i 0 (concatD [prt 0 e_, doc (showString "=>"), prt 0 s])

instance Print [AbsE.VarBind] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsE.VarBind where
  prt i = \case
    AbsE.JustVar id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsE.VarIs id_ e_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 e_])

instance Print AbsE.E where
  prt i = \case
    AbsE.EmptyTuple -> prPrec i 13 (concatD [doc (showString "("), doc (showString ")")])
    AbsE.Tuple e_ es -> prPrec i 13 (concatD [doc (showString "("), prt 0 e_, doc (showString ","), prt 0 es, doc (showString ")")])
    AbsE.HexInt hexinteger -> prPrec i 13 (concatD [prt 0 hexinteger])
    AbsE.Int n -> prPrec i 13 (concatD [prt 0 n])
    AbsE.Var id_ -> prPrec i 13 (concatD [prt 0 id_])
    AbsE.String str -> prPrec i 13 (concatD [printString str])
    AbsE.ConRecord uident efields -> prPrec i 13 (concatD [prt 0 uident, doc (showString "{"), prt 0 efields, doc (showString "}")])
    AbsE.Con uident -> prPrec i 13 (concatD [prt 0 uident])
    AbsE.Wild -> prPrec i 13 (concatD [doc (showString "_")])
    AbsE.PlusPlusPost e_ -> prPrec i 12 (concatD [prt 12 e_, doc (showString "++")])
    AbsE.MinusMinusPost e_ -> prPrec i 12 (concatD [prt 12 e_, doc (showString "--")])
    AbsE.Index e_1 e_2 -> prPrec i 12 (concatD [prt 12 e_1, doc (showString "["), prt 0 e_2, doc (showString "]")])
    AbsE.Dot e_ id_ -> prPrec i 12 (concatD [prt 12 e_, doc (showString "."), prt 0 id_])
    AbsE.Bang e_1 e_2 -> prPrec i 12 (concatD [prt 12 e_1, doc (showString "!"), prt 13 e_2])
    AbsE.Arrow e_ id_ -> prPrec i 12 (concatD [prt 12 e_, doc (showString "->"), prt 0 id_])
    AbsE.App e_1 e_2 -> prPrec i 12 (concatD [prt 12 e_1, prt 13 e_2])
    AbsE.PlusPlusPre e_ -> prPrec i 11 (concatD [doc (showString "++"), prt 11 e_])
    AbsE.MinusMinusPre e_ -> prPrec i 11 (concatD [doc (showString "--"), prt 11 e_])
    AbsE.Negate e_ -> prPrec i 11 (concatD [doc (showString "-"), prt 11 e_])
    AbsE.Not e_ -> prPrec i 11 (concatD [doc (showString "!"), prt 11 e_])
    AbsE.BitwiseNot e_ -> prPrec i 11 (concatD [doc (showString "~"), prt 11 e_])
    AbsE.Deref e_ -> prPrec i 11 (concatD [doc (showString "*"), prt 11 e_])
    AbsE.AddressOf e_ -> prPrec i 11 (concatD [doc (showString "&"), prt 11 e_])
    AbsE.Mul e_1 e_2 -> prPrec i 10 (concatD [prt 10 e_1, doc (showString "*"), prt 11 e_2])
    AbsE.Div e_1 e_2 -> prPrec i 10 (concatD [prt 10 e_1, doc (showString "/"), prt 11 e_2])
    AbsE.Mod e_1 e_2 -> prPrec i 10 (concatD [prt 10 e_1, doc (showString "%"), prt 11 e_2])
    AbsE.Plus e_1 e_2 -> prPrec i 9 (concatD [prt 9 e_1, doc (showString "+"), prt 10 e_2])
    AbsE.Minus e_1 e_2 -> prPrec i 9 (concatD [prt 9 e_1, doc (showString "-"), prt 10 e_2])
    AbsE.Shl e_1 e_2 -> prPrec i 8 (concatD [prt 8 e_1, doc (showString "<<"), prt 9 e_2])
    AbsE.Shr e_1 e_2 -> prPrec i 8 (concatD [prt 8 e_1, doc (showString ">>"), prt 9 e_2])
    AbsE.MyLT e_1 e_2 -> prPrec i 7 (concatD [prt 7 e_1, doc (showString "<"), prt 8 e_2])
    AbsE.LTE e_1 e_2 -> prPrec i 7 (concatD [prt 7 e_1, doc (showString "<="), prt 8 e_2])
    AbsE.MyGT e_1 e_2 -> prPrec i 7 (concatD [prt 7 e_1, doc (showString ">"), prt 8 e_2])
    AbsE.GTE e_1 e_2 -> prPrec i 7 (concatD [prt 7 e_1, doc (showString ">="), prt 8 e_2])
    AbsE.Eq e_1 e_2 -> prPrec i 6 (concatD [prt 6 e_1, doc (showString "=="), prt 7 e_2])
    AbsE.NEq e_1 e_2 -> prPrec i 6 (concatD [prt 6 e_1, doc (showString "!="), prt 7 e_2])
    AbsE.BitwiseAnd e_1 e_2 -> prPrec i 5 (concatD [prt 5 e_1, doc (showString "&"), prt 6 e_2])
    AbsE.BitwiseXor e_1 e_2 -> prPrec i 4 (concatD [prt 4 e_1, doc (showString "^"), prt 5 e_2])
    AbsE.BitwiseOr e_1 e_2 -> prPrec i 3 (concatD [prt 3 e_1, doc (showString "|"), prt 4 e_2])
    AbsE.And e_1 e_2 -> prPrec i 2 (concatD [prt 2 e_1, doc (showString "&&"), prt 3 e_2])
    AbsE.Or e_1 e_2 -> prPrec i 1 (concatD [prt 1 e_1, doc (showString "||"), prt 2 e_2])
    AbsE.Assign e_1 aop e_2 -> prPrec i 0 (concatD [prt 1 e_1, prt 0 aop, prt 0 e_2])
    AbsE.TypeAnnot e_ t -> prPrec i 0 (concatD [prt 1 e_, doc (showString "::"), prt 0 t])

instance Print [AbsE.E] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsE.EField] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsE.EField where
  prt i = \case
    AbsE.EField id_ e_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 e_])

instance Print AbsE.AOp where
  prt i = \case
    AbsE.EqEq -> prPrec i 0 (concatD [doc (showString "=")])
    AbsE.PlusEq -> prPrec i 0 (concatD [doc (showString "+=")])
    AbsE.MinusEq -> prPrec i 0 (concatD [doc (showString "-=")])
    AbsE.MulEq -> prPrec i 0 (concatD [doc (showString "*=")])
    AbsE.DivEq -> prPrec i 0 (concatD [doc (showString "/=")])
    AbsE.ModEq -> prPrec i 0 (concatD [doc (showString "%=")])
    AbsE.ShlEq -> prPrec i 0 (concatD [doc (showString "<<=")])
    AbsE.ShrEq -> prPrec i 0 (concatD [doc (showString ">>=")])
    AbsE.AndEq -> prPrec i 0 (concatD [doc (showString "&=")])
    AbsE.XorEq -> prPrec i 0 (concatD [doc (showString "^=")])
    AbsE.OrEq -> prPrec i 0 (concatD [doc (showString "|=")])

instance Print AbsE.T where
  prt i = \case
    AbsE.TArrow t1 t2 -> prPrec i 0 (concatD [prt 1 t1, doc (showString "->"), prt 0 t2])
    AbsE.TVar id_ -> prPrec i 2 (concatD [prt 0 id_])
    AbsE.TNat n -> prPrec i 2 (concatD [prt 0 n])
    AbsE.TCon uident -> prPrec i 2 (concatD [prt 0 uident])
    AbsE.TEmptyTup -> prPrec i 2 (concatD [doc (showString "("), doc (showString ")")])
    AbsE.TTup t ts -> prPrec i 2 (concatD [doc (showString "("), prt 0 t, doc (showString ","), prt 0 ts, doc (showString ")")])
    AbsE.TApp t1 t2 -> prPrec i 1 (concatD [prt 1 t1, prt 2 t2])
    AbsE.TArray t1 t2 -> prPrec i 0 (concatD [prt 1 t1, doc (showString "["), prt 0 t2, doc (showString "]")])

instance Print [AbsE.T] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]
