-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelE where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsE

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsE.Ident -> Result
transIdent x = case x of
  AbsE.Ident string -> failure x

transUIdent :: AbsE.UIdent -> Result
transUIdent x = case x of
  AbsE.UIdent string -> failure x

transInfix :: AbsE.Infix -> Result
transInfix x = case x of
  AbsE.Infix string -> failure x

transHexInteger :: AbsE.HexInteger -> Result
transHexInteger x = case x of
  AbsE.HexInteger string -> failure x

transM :: AbsE.M -> Result
transM x = case x of
  AbsE.Module ds -> failure x

transD :: AbsE.D -> Result
transD x = case x of
  AbsE.Default uident t -> failure x
  AbsE.Defun ident e s -> failure x
  AbsE.Instance ident t e s -> failure x
  AbsE.TySig ident t -> failure x
  AbsE.KindSig uident t -> failure x
  AbsE.TySyn conargs t -> failure x
  AbsE.Import modulename -> failure x
  AbsE.Global globalregion varbind -> failure x
  AbsE.Data conargs datarhs -> failure x
  AbsE.Tag conargs t contags -> failure x

transConArgs :: AbsE.ConArgs -> Result
transConArgs x = case x of
  AbsE.CANil uident -> failure x
  AbsE.CACons conargs ident -> failure x

transModuleName :: AbsE.ModuleName -> Result
transModuleName x = case x of
  AbsE.MNil uident -> failure x
  AbsE.MCons uident modulename -> failure x

transGlobalRegion :: AbsE.GlobalRegion -> Result
transGlobalRegion x = case x of
  AbsE.Memory -> failure x
  AbsE.Storage -> failure x
  AbsE.TStorage -> failure x
  AbsE.Code -> failure x

transDataRHS :: AbsE.DataRHS -> Result
transDataRHS x = case x of
  AbsE.Boxed unboxedrhs ident -> failure x
  AbsE.Unboxed unboxedrhs -> failure x

transUnboxedRHS :: AbsE.UnboxedRHS -> Result
transUnboxedRHS x = case x of
  AbsE.URHS datacons -> failure x

transDataCon :: AbsE.DataCon -> Result
transDataCon x = case x of
  AbsE.DCArgs dca -> failure x
  AbsE.DCRecord uident recordfields -> failure x

transDCA :: AbsE.DCA -> Result
transDCA x = case x of
  AbsE.DCANil uident -> failure x
  AbsE.DCACons dca t -> failure x

transRecordField :: AbsE.RecordField -> Result
transRecordField x = case x of
  AbsE.RF ident t -> failure x

transConTag :: AbsE.ConTag -> Result
transConTag x = case x of
  AbsE.ConTag uident e -> failure x

transS :: AbsE.S -> Result
transS x = case x of
  AbsE.SE e -> failure x
  AbsE.If e s1 s2 -> failure x
  AbsE.While e s -> failure x
  AbsE.Return e -> failure x
  AbsE.Do ss -> failure x
  AbsE.Case e cases -> failure x
  AbsE.Break -> failure x
  AbsE.Continue -> failure x
  AbsE.For s1 e s2 s3 -> failure x
  AbsE.Declare varbinds -> failure x

transCASE :: AbsE.CASE -> Result
transCASE x = case x of
  AbsE.C e s -> failure x

transVarBind :: AbsE.VarBind -> Result
transVarBind x = case x of
  AbsE.JustVar ident -> failure x
  AbsE.VarIs ident e -> failure x

transE :: AbsE.E -> Result
transE x = case x of
  AbsE.EmptyTuple -> failure x
  AbsE.Tuple e es -> failure x
  AbsE.HexInt hexinteger -> failure x
  AbsE.Int integer -> failure x
  AbsE.Var ident -> failure x
  AbsE.String string -> failure x
  AbsE.ConRecord uident efields -> failure x
  AbsE.Con uident -> failure x
  AbsE.Wild -> failure x
  AbsE.PlusPlusPost e -> failure x
  AbsE.MinusMinusPost e -> failure x
  AbsE.Index e1 e2 -> failure x
  AbsE.Dot e ident -> failure x
  AbsE.Bang e1 e2 -> failure x
  AbsE.Arrow e ident -> failure x
  AbsE.App e1 e2 -> failure x
  AbsE.PlusPlusPre e -> failure x
  AbsE.MinusMinusPre e -> failure x
  AbsE.Negate e -> failure x
  AbsE.Not e -> failure x
  AbsE.BitwiseNot e -> failure x
  AbsE.Deref e -> failure x
  AbsE.AddressOf e -> failure x
  AbsE.Mul e1 e2 -> failure x
  AbsE.Div e1 e2 -> failure x
  AbsE.Mod e1 e2 -> failure x
  AbsE.Plus e1 e2 -> failure x
  AbsE.Minus e1 e2 -> failure x
  AbsE.Shl e1 e2 -> failure x
  AbsE.Shr e1 e2 -> failure x
  AbsE.MyLT e1 e2 -> failure x
  AbsE.LTE e1 e2 -> failure x
  AbsE.MyGT e1 e2 -> failure x
  AbsE.GTE e1 e2 -> failure x
  AbsE.Eq e1 e2 -> failure x
  AbsE.NEq e1 e2 -> failure x
  AbsE.BitwiseAnd e1 e2 -> failure x
  AbsE.BitwiseXor e1 e2 -> failure x
  AbsE.BitwiseOr e1 e2 -> failure x
  AbsE.And e1 e2 -> failure x
  AbsE.Or e1 e2 -> failure x
  AbsE.Assign e1 aop e2 -> failure x
  AbsE.TypeAnnot e t -> failure x

transEField :: AbsE.EField -> Result
transEField x = case x of
  AbsE.EField ident e -> failure x

transAOp :: AbsE.AOp -> Result
transAOp x = case x of
  AbsE.EqEq -> failure x
  AbsE.PlusEq -> failure x
  AbsE.MinusEq -> failure x
  AbsE.MulEq -> failure x
  AbsE.DivEq -> failure x
  AbsE.ModEq -> failure x
  AbsE.ShlEq -> failure x
  AbsE.ShrEq -> failure x
  AbsE.AndEq -> failure x
  AbsE.XorEq -> failure x
  AbsE.OrEq -> failure x

transT :: AbsE.T -> Result
transT x = case x of
  AbsE.TArrow t1 t2 -> failure x
  AbsE.TVar ident -> failure x
  AbsE.TNat integer -> failure x
  AbsE.TCon uident -> failure x
  AbsE.TEmptyTup -> failure x
  AbsE.TTup t ts -> failure x
  AbsE.TApp t1 t2 -> failure x
  AbsE.TArray t1 t2 -> failure x
