

module EVMC.Abs where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
newtype UIdent = UIdent String deriving (Eq, Ord, Show, Read)
data D = TySig Ident T | Defun Ident Pat [S] | TestExpr E
  deriving (Eq, Ord, Show, Read)

data Pat
    = PVar Ident
    | PCon UIdent
    | PEmptyTup
    | PTup Pat [Pat]
    | PStruct [PField]
    | PApp Pat Pat
  deriving (Eq, Ord, Show, Read)

data PField = PFieldAnon Pat | PFieldNamed Ident Pat
  deriving (Eq, Ord, Show, Read)

data S = Assign Pat E | Pass
  deriving (Eq, Ord, Show, Read)

data T
    = TInt Integer
    | TVar Ident
    | TCon UIdent
    | TEmptyTup
    | TTup T [T]
    | TApp T T
    | TFun T T
  deriving (Eq, Ord, Show, Read)

data Region = Memory
  deriving (Eq, Ord, Show, Read)

data E = EInt Integer
  deriving (Eq, Ord, Show, Read)

data ArgList = ArgList E [E]
  deriving (Eq, Ord, Show, Read)

data EField = FieldAnon E | FieldNamed Ident E
  deriving (Eq, Ord, Show, Read)

