{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module EVMC.Print where

-- pretty-printer generated by the BNF converter

import EVMC.Abs
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))


instance Print UIdent where
  prt _ (UIdent i) = doc (showString ( i))



instance Print D where
  prt i e = case e of
    TySig id t -> prPrec i 0 (concatD [prt 0 id, doc (showString "::"), prt 0 t])
    Defun id pat ss -> prPrec i 0 (concatD [prt 0 id, prt 1 pat, doc (showString "="), doc (showString "{"), prt 0 ss, doc (showString "}")])
    TestExpr e_ -> prPrec i 0 (concatD [doc (showString "testE"), prt 0 e_])

instance Print Pat where
  prt i e = case e of
    PVar id -> prPrec i 1 (concatD [prt 0 id])
    PCon uident -> prPrec i 1 (concatD [prt 0 uident])
    PEmptyTup -> prPrec i 1 (concatD [doc (showString "("), doc (showString ")")])
    PTup pat pats -> prPrec i 1 (concatD [doc (showString "("), prt 0 pat, doc (showString ","), prt 0 pats, doc (showString ")")])
    PStruct pfields -> prPrec i 1 (concatD [doc (showString "{"), prt 0 pfields, doc (showString "}")])
    PApp pat1 pat2 -> prPrec i 0 (concatD [prt 0 pat1, prt 1 pat2])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print PField where
  prt i e = case e of
    PFieldAnon pat -> prPrec i 0 (concatD [prt 0 pat])
    PFieldNamed id pat -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 pat])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print S where
  prt i e = case e of
    Assign pat e_ -> prPrec i 0 (concatD [prt 0 pat, doc (showString "="), prt 0 e_])
    Pass -> prPrec i 0 (concatD [doc (showString "pass")])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ";"), prt 0 xs])
instance Print T where
  prt i e = case e of
    TInt n -> prPrec i 2 (concatD [prt 0 n])
    TVar id -> prPrec i 2 (concatD [prt 0 id])
    TCon uident -> prPrec i 2 (concatD [prt 0 uident])
    TEmptyTup -> prPrec i 2 (concatD [doc (showString "("), doc (showString ")")])
    TTup t ts -> prPrec i 2 (concatD [doc (showString "("), prt 0 t, doc (showString ","), prt 0 ts, doc (showString ")")])
    TApp t1 t2 -> prPrec i 1 (concatD [prt 1 t1, prt 2 t2])
    TFun t1 t2 -> prPrec i 0 (concatD [prt 1 t1, doc (showString "->"), prt 0 t2])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Region where
  prt i e = case e of
    Memory -> prPrec i 0 (concatD [doc (showString "Memory")])

instance Print E where
  prt i e = case e of
    EInt n -> prPrec i 2 (concatD [prt 0 n])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print ArgList where
  prt i e = case e of
    ArgList e_ es -> prPrec i 0 (concatD [doc (showString "("), prt 0 e_, doc (showString ","), prt 0 es, doc (showString ")")])

instance Print EField where
  prt i e = case e of
    FieldAnon e_ -> prPrec i 0 (concatD [prt 0 e_])
    FieldNamed id e_ -> prPrec i 0 (concatD [prt 0 id, doc (showString ":"), prt 0 e_])


