module EVMC.Skel where

-- Haskell module generated by the BNF converter

import EVMC.Abs
import EVMC.ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transUIdent :: UIdent -> Result
transUIdent x = case x of
  UIdent string -> failure x
transD :: D -> Result
transD x = case x of
  TySig ident t -> failure x
  Defun ident pat ss -> failure x
  TestExpr e -> failure x
  TestS s -> failure x
  TestPat pat -> failure x
transPat :: Pat -> Result
transPat x = case x of
  PWild -> failure x
  PVar ident -> failure x
  PCon uident -> failure x
  PEmptyTup -> failure x
  PTup pat pats -> failure x
  PEmptyStruct -> failure x
  PStruct pfields -> failure x
  PApp pat1 pat2 -> failure x
transPField :: PField -> Result
transPField x = case x of
  PFieldAnon pat -> failure x
  PFieldNamed ident pat -> failure x
transS :: S -> Result
transS x = case x of
  Assign pat e -> failure x
  Pass -> failure x
transT :: T -> Result
transT x = case x of
  TInt integer -> failure x
  TVar ident -> failure x
  TCon uident -> failure x
  TEmptyTup -> failure x
  TTup t ts -> failure x
  TEmptyStruct -> failure x
  TStruct tfields -> failure x
  TApp t1 t2 -> failure x
  TFun t1 t2 -> failure x
transTField :: TField -> Result
transTField x = case x of
  TFieldAnon t -> failure x
  TFieldNamed ident t -> failure x
transRegion :: Region -> Result
transRegion x = case x of
  Memory -> failure x
transE :: E -> Result
transE x = case x of
  EInt integer -> failure x
  EVar ident -> failure x
  EEmptyTup -> failure x
  ETup e es -> failure x
transArgList :: ArgList -> Result
transArgList x = case x of
  ArgList e es -> failure x
transEField :: EField -> Result
transEField x = case x of
  FieldAnon e -> failure x
  FieldNamed ident e -> failure x

